### ISSUE TITLE
Channels and message ordering question

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#10]
I did this:
    let send1,recv1 = CloudChannel.New<string>() |> cluster.Run

    cloud { for i in 0 .. 99 do 
               do! CloudChannel.Send (sprintf "hello%d" i) send1  }
     |> cluster.Run

    cloud { let results = ResizeArray()
            for i in 0 .. 99 do 
               let! msg = CloudChannel.Receive(recv1)
               results.Add msg
            return results.ToArray() }
     |> cluster.Run

and was somewhat surprised to see messages arriving down the channel out of order - I had expected message ordering to at least be guaranteed between one sender and one receiver.

    [|"hello13"; "hello15"; "hello14"; "hello12"; "hello0"; "hello1"; "hello2";
      ...
      "hello99"; "hello96"|]

What are the guarantees here?

I went looking for docs too but didn't see anything on channels here http://www.m-brace.net/programming-model.html

thanks
don

**Comment by krontogiannis** [comment]
Hello!
I pushed a fix yesterday that removed partitioning from the underlying queue [81634d7](https://github.com/mbraceproject/MBrace.Azure/commit/81634d7193e5b3e2ca469c05e5bf24db980f7b11), so now ordering should be ok when using one sender and one receiver.

Nevertheless, I'm not so sure that this was a 'bug'. One should use an ICloudChannel implementations that fits his needs. 

The m-brace.net docs are outdated (they are for the 0.5.* MBrace.Core) that didn't include channels.

**Comment by dsyme** [comment]
OK, thanks!  

I guess the question becomes what delivery defaults are guaranteed by CloudChannel.New, which need to be documented - it's a MBrace.Core thing though, presumably.

**Comment by eiriktsarpalis** [comment]
Hi Don,

The CloudChannel spec has been left deliberately ambiguous because it largely depends on the underlying implementation. I find it plausible that certain runtimes may not offer FIFO guarantees. Another point of ambiguity, for instance, is whether multiple recipients are supported. Azure queues support them, whereas a different implementation could not even permit serialisation of the receive port.

**Comment by krontogiannis** [comment]
Just a correction, the default channel provider used my MBrace.Azure is not _Azure_ Queues, it's _Service Bus_ Queues. The current implementation offers multiple senders/receivers (both ports are serializable). The old implementation that used partitioned queues had better scaling, but could not guarantee FIFO.

Since you are able to easily supply your own implementation when using `.CreateProcess` I think the only issue is if we want to provide different flavors of channels in the `MBrace.Azure.Store` library.

**Comment by eiriktsarpalis** [comment]
@krontogiannis Do you think it would be reasonable to allow the user to pick behaviour? I can imagine that there are applications where FIFO is not important but scalability is.

**Comment by krontogiannis** [comment]
Well I can think of an implementation with
* 1 to 1 FIFO guarantee.
* Using partitioned queues for n to n scalability.
* Multiple underlying queues
* Azure Queue implementation for lower latency compared to Service Bus.

I think `MBrace.Azure.Store` could include `1` and `2`, but I'm not sure which one should be the default.

**Comment by dsyme** [comment]
Yes, it feels like having both 1:1 and partitioned queues in the core model.  Additional further queue options in MBrace.Azure would make it both unified and pragmatic.

If you have partitioned channels (which I don't think are in the version I'm using), how do you process them?  Is there a CloudStream.ofChannels or the like?

In practice, I think MBrace will likely very often be used in contexts where data is streaming in via a range of heterogeneous queues which are not under the architectural control of the team who are using MBrace.  For example, they may be able to arrange for some data team to stream data into a ZeroMQ or RabbitMQ queue. Giving consistent, easy to use connectors that allow you to take most existing queues (and other sources of data) and connect them into a running MBrace architecture would seem to be compelling.

**Comment by krontogiannis** [comment]
* In your version the underlying queue is automatically partitioned, that why you get messages out of order even with one receiver.

* Using different Channel providers/implementations is possible. You can do something like
```fsharp
let channel1Job = runtime.CreateProcess(CloudChannel.New()) // thats the default servive bus queue implementation

let rabbitMQ = SomeRabbitMQProviderImpl() :> ICloudChannelProvider
let rabbitMQJob = runtime.CreateProcess(CloudChannel.New(), channelProvider = rabbitMQ)
```
and have channels with different semantics or features.

* Combining CloudStreams with CloudChannels is not available now. We should open a discussion in MBrace.Core about this though and get @palladin to participate.

**Comment by palladin** [comment]
CloudStream.ofChannel/toChannel is a big priority for me because it will enable many interesting
dataflow-oriented scenarios. So, stay tuned!

**Comment by dsyme** [comment]
@krontogiannis -  I'm planning on poking around with ICloudChannelProvider out of curiosity. 

This would presumably replace all channels _created_ by a specific process?  But what if the process closes over other channels from a different provider?   Is mix-and-match allowed? (The same question applies to storage primitives CloudRef etc.)

**Comment by krontogiannis** [comment]
I think this depends on the implementation of each `ICloudChannelProvider/ICloudChannel`, etc.
If the `ICloudChannel` implementation doesn't use a pattern like `Workflow.GetResource<ICloudChannelProvider>` (which gets the process' default provider) in its instance members then mix-and-match should be possible.

**Comment by dsyme** [comment]
I'm closing this since the original question has been answered.

I still have some questions about the overall utility of the CloudChannel abstraction - basically, is it useful?  I've been looking at the variety of queue-like options available on Azure and AWS and it's not clear to me that CloudChannel is really such a useful abstraction over these - there are too many kinds of queues with too many tradeoffs (e.g. visibility windows, partitioning, batching, FIFO). Right now I find it hard to imagine writing code that just passes around CloudChannel (or ISendPort/IRecvPort) without regard to at least some characterization of the specific queue I'm working with. 

Another way of asking that is whether MBrace would be simpler if we just removed ISendPort/IRecvPort/ChannelProvider and instead characterized some of the kinds of queues that are available in both AWS and Azure - perhaps even in a single type CloudQueue.  That would seem simpler.

However I'll put those thoughts together in another issue for MBrace.Core.
