### ISSUE TITLE
Serializing BlobStore instances exposes connection strings

### ISSUE THREAD

**Issue by eiriktsarpalis** [mbraceproject/MBrace.Azure#105]
Should be refactored so that serialization makes use of `ConfigurationId`.

**Comment by dsyme** [comment]
Hi @eiriktsarpalis What's the status on this?

**Comment by eiriktsarpalis** [comment]
@dsyme this has been fixed as of 0.10. It can be closed.

**Comment by dsyme** [comment]
Great!
