### ISSUE TITLE
Subscription name validation does not allow spaces

### ISSUE THREAD

**Issue by alexr1993** [mbraceproject/MBrace.Azure#109]
The subscription name validation enforces the naming conventions of Microsoft service bus detailed here: https://msdn.microsoft.com/en-us/library/azure/dd179349.aspx

Subscription names can however have spaces, meaning valid subscriptions are being denied by the validation.

Current location of validation:
https://github.com/mbraceproject/MBrace.Azure/blob/master/src/MBrace.Azure/Common/Validation.fs

Original location of validation with comment referencing service bus naming
https://github.com/mbraceproject/MBrace.Azure/commit/37b604aa4a308f9baad06392a8add1181d05593a#diff-490038deaf2ec6f03bc9f27df0c38f26

**Comment by palladin** [comment]
The only use of subscriptionName is here
https://github.com/mbraceproject/MBrace.Azure/blob/master/src/MBrace.Azure/Runtime/WorkItemManager/WorkItemManager.fs#L98 and it is used for subscription on topics.

**Comment by palladin** [comment]
I think that the subscriptionName validation is ok can you give more details about the Subscription name that you are referring?

**Comment by alexr1993** [comment]
Ah apologies -- our logging was being truncated so it is likely that our name was wrong. I don't know for sure what the name was that was causing the problem but deleting the topics and letting them re-spawn appears to have fixed this issue.

Thanks for your help, we just had some teething issue when updating versions.

**Comment by palladin** [comment]
Oh cool, you can always call cluster.Reset to clean up queues, topics etc
