### ISSUE TITLE
CloudAtom.Read not returning

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#11]
I'm using the Elastacloud preview. I do:

    let atom = CloudAtom.New(100) |> cluster.Run

    // Check the unique ID of the atom
    atom.Id

which is fine, and then do this

    // Get the value of the atom
    let atomValue = atom  |> CloudAtom.Read |> cluster.Run

but that hangs, the process never returns.

I've tried several times but it's the same each time. Is this a known issue?

Thanks
don

**Comment by krontogiannis** [comment]
I'm not able to reproduce it on our master branch. I believe this was a deserialization issue on CloudAtom that is fixed now. Is `cluster.ShowLogs` any helpful?

**Comment by eiriktsarpalis** [comment]
Hmm, I ran this a few of times (using the brisk version) but couldn't reproduce it. Does your runtime hang with every computation afterwards or just that one?

**Comment by dsyme** [comment]
Just that one, it seems to always reliably hang on that.

**Comment by dsyme** [comment]
Yes, there's a fault shown in the logs.  BTW a cluster.ClearLogs() would be pretty useful (since they get pretty long and clearing them beforehand to see recent activity would be one way to manage that).  Likewise a cluster.ShowLogs(timespan) which shows entries for the specified period. 

```
 worker:MBraceWorkerRole_IN_0             23/02/2015 20:00:32 +00:00  WORKER FAULT: Nessos.FsPickler.FsPicklerException: FsPickler: Type load error. ---> System.TypeLoadException: Could not load type 'Microsoft.FSharp.Control.AsyncBuilderImpl+callA@813' from assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at Nessos.FsPickler.ReflectionCache.loadMemberInfo(FSharpOption`1 tyConv, FSharpFunc`2 loadAssembly, FSharpFunc`2 getMethodSignature, CompositeMemberInfo mI) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\ReflectionCache.fs:line 175
   --- End of inner exception stack trace ---
   at Nessos.FsPickler.ReflectionCache.loadMemberInfo(FSharpOption`1 tyConv, FSharpFunc`2 loadAssembly, FSharpFunc`2 getMethodSignature, CompositeMemberInfo mI) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\ReflectionCache.fs:line 227
   at Nessos.FsPickler.Utils.BiMemoizer`2.G(S s) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Utils\Utils.fs:line 136
```

**Comment by krontogiannis** [comment]
@dsyme Sure, [Client API](https://github.com/mbraceproject/MBrace.Azure/blob/new-core-temp/src/MBrace.Azure.Client/Client.fs) includes
```fsharp
.ShowLogs(?worker : IWorkerRef, ?fromDate : DateTimeOffset, ?toDate : DateTimeOffset) 
```
It's just not available on the Brisk version.

**Comment by dsyme** [comment]
Great!  Once again, what I want is already done, that's a really good sign  :) 

Looking forward to having the Brisk version updated.

**Comment by eiriktsarpalis** [comment]
@dsyme, this issue seems to be caused by a disparity between the FSharp.Core in the Azure deployment and the FSharp.Core in your local machine. This is unfortunately an issue of type name rather than assembly version, so it cannot be fixed by binding redirects. It relates to the generated suffix of the internal function type (`@813`) which can differ from build to build.

**Comment by dsyme** [comment]
Ah, I see, well, that is pretty problematic. It is certainly true that FSharpAsync are not consistently serializable from FSharp.Core version to version, I didn't realize you were relying on that. What thoughts do you have on addressing this? I might expect async values of my own to not be serializable (while cloud { ... } would be), but it certainly comes as a surprise if using a library primitive like CloudAtom.Read serializes a dodgy value.  Perhaps this will have been improved by the new release which uses ``Cloud<_>`` everywhere?

 (Also, I suppose the error shouldn't have been manifest as a silent worker failure...?)

**Comment by eiriktsarpalis** [comment]
In general, there is no easy way to solve this unfortunately. But there can be a certain degree of damage control. I would suspect that the particular case fails by virtue of some direct call to the F# core. In my experience such issues tend to go away when wrapping such code in async blocks, thus delaying the call and avoiding build-specific stuff being caught in the serialised closures. We have fixed quite a few bugs of this sort in the core library, so I would suspect this is not an issue in the master branch.

The master branch comes with fault policies [[1](https://github.com/mbraceproject/MBrace.Core/blob/master/src/MBrace.Core/Runtime/FaultPolicy.fs),[2](https://github.com/mbraceproject/MBrace.Core/blob/master/src/MBrace.Core/Runtime/RuntimeCombinators.fs#L329)] which refine behaviour in the event of a fault. The Brisk version doesn't come with any of that.

**Comment by eiriktsarpalis** [comment]
As regards the original issue, a temporary workaround would be to wrap `CloudAtom.Read` function in a cloud block:
```fsharp
cloud { return! CloudAtom.Read atom } |> cluster.Run
```

**Comment by dsyme** [comment]
Yes, wrapping in workflows (or equivalently cloud.Delay, or async.Delay) is a way to ensure the objects being specified have a code+data realization that only refers to public API. 

My impression that the problem will always be caused by MBrace implementation code that applies F# library combinators for async, e.g. async.Return.

Tricky problem, but useful that the async { ... } and cloud { ... } criteria should be enough.

I suppose the cluster workers will eventually run FSharp.Core 4.4.0.0, (i.e. latest available)

**Comment by eiriktsarpalis** [comment]
It's pretty much a minefield, any piece of otherwise innocent looking user code could potentially trigger this issue: from capturing curried FSharp.Core functions in the closure to simply using the `dict` combinator. Just like capturing nonserializable objects, we should anticipate such types of errors and present them to the user in the clearest possible way.

**Comment by dsyme** [comment]
I'll close this specific issue for now
