### ISSUE TITLE
Partial job failure and getting results

### ISSUE THREAD

**Issue by cgravill** [mbraceproject/MBrace.Azure#111]
We’re running some fairly large simulations. As is reasonable, it appears over the course of the long code execution some machines have “died”. When we attempt to get the results we get an error like:

```
MBrace.Core.FaultException: Job 'e5d2f005b630416a92ef69ffb67de0e6' was being processed by worker 'MBraceAzureRole_IN_14' which has died.
   at Cloud.Parallel(seq<Cloud<Tuple`2>> computations)
--- End of stack trace from previous location where exception was thrown ---
   at <StartupCode$MBrace-Runtime-Core>.$CloudTask.AwaitResult@101-2.Invoke(TaskResult _arg2)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@787-1.Invoke(a a)
   at MBrace.Core.Internals.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken)
   at MBrace.Runtime.CloudTask`1.get_ResultBoxed()
   at <StartupCode$FSI_0026>.$FSI_0026.main@()
Stopped due to error
```

Is it possible to recover the individual results, possibly by the jobs themselves? I've explored the API and haven't found how to get the jobs out  

We’ve repeated this a few times and the probability of something going wrong at the scale we need to run is fairly high. We’re completely fine with having gaps.

We start the jobs with Cloud.Parallel:

``` F#
    [n1 .. n2]
    |> List.map (fun i -> cloud { return i, run_simulation prog })
    |> Cloud.Parallel
    |> cluster.CreateProcess
```

It’s bit less convenient but would the recommendation be to start individual processes ourselves?

**Comment by eiriktsarpalis** [comment]
Hi Colin,

There are a couple of ways in which you can address this problem. Assuming that you expect your machines to fail often, you could specify a different fault policy, one that will always repeat a faulted job:
```fsharp
let workflow =
    [n1 .. n2]
    |> List.map (fun i -> cloud { return i, run_simulation prog })
    |> Cloud.Parallel

cluster.CreateProcess(workflow, faultPolicy = FaultPolicy.InfiniteRetry())
```
Note that you can create custom fault policies by implementing instances of the record:
```fsharp
type FaultPolicy = { Policy : int -> exn -> TimeSpan option }
```
Where the integer parameter specifies the number of faults recorded for the specific job and the exception specifies the type of fault. The return value is `None` if no retries are to be made and `Some` if a retry is to be made after a given timespan.

Another option is to create processes as individual tasks, as you said:
```fsharp

[n1 .. n2]
|> List.map (fun i -> cluster.CreateProcess(cloud { return i, run_simulation prog }, target = <optional target worker>)
```
This will return an list of CloudTasks that can be monitored individually. It should be noted that it is possible to create tasks from the cloud as well:
```fsharp
open MBrace.Library
cloud {
    return! [n1 .. n2] |> Local.Sequential.map (fun i -> Cloud.StartAsTask(cloud { return i, run_simulation prog }))
} |> cluster.Run
```

**Comment by cgravill** [comment]
Great, that's very useful, thanks. I'm using a variant on

``` F#
[n1 .. n2]
|> List.map (fun i -> cluster.CreateProcess(cloud { return i, run_simulation prog })
```

It takes quite a while to do the actual process creation compared to Cloud.Parallel. I switched do doing it async which is somewhat better:

``` F#
[n1 .. n2]
|> List.map (fun i -> cluster.CreateProcessAsync(cloud { return i, run_simulation prog })
|> Async.Parallel
|> Async.RunSynchronously
```

It's still taking a while and seemingly doing a lot of network transfer. Is it sending all the dependencies on a per CreateProcess* basis?

Using the FaultPolicy could we then implement dropping failure? It seems like FaultPolicy is only to say how long to retry:

``` F#
/// Makes no attempt at retrying, raising fault exception at the first occurrence.
static member NoRetry = { Policy = fun _ _ -> None }
```
So I'd like no attempt at retrying, but don't raise an exception.

**Comment by eiriktsarpalis** [comment]
Yes, every ``cluster.CreateProcess`` will upload a separate computation independently and this can be slow depending on your internet connection and the data dependencies you are referencing. This why I recommend using the equivalent ``Cloud.StartAsTask`` (given as the last example in my previous post). This will again create independent tasks but these do not come with an upload penalty since their creation happens within the azure data center.

It's not currently possible to use a fault policy to force not raising an exception. In cases where partial results are important, I would recommend using ``Cloud.StartAsTask`` instead of ``Cloud.Parallel``. 

It's probably worth pointing out that "faults" in the context of MBrace usually mean worker deaths. As far as user exceptions are concerned, partial results can be enforced in ``Cloud.Parallel`` using the following implementation:
```fsharp
let parallelPartial (computations : seq<Cloud<'T>>) : Cloud<Choice<'T, exn> []> = cloud {
    let catch c = cloud { 
        try 
            let! r = in c 
            return Choice1Of2 r 
        with e -> 
            return Choice2Of2 e }

    return! computations |> Seq.map catch |> Cloud.Parallel
}
```

**Comment by eiriktsarpalis** [comment]
As of MBrace.Core 0.10.9 it is possible to silence fault exceptions using the following trick:
```fsharp
let parallelProtected (computations : seq<Cloud<'T>>) : Cloud<'T option []> = cloud {
    let protect (computation : Cloud<'T>) = cloud {
        // detect if computation runs as result of retry to a faulted computation
        let! isFaulted = Cloud.IsPreviouslyFaulted
        if isFaulted then return None
        else
            let! t = computation
            return Some t
    }

    return! 
        computations 
        |> Seq.map protect 
        |> Cloud.Parallel 
        |> Cloud.WithFaultPolicy (FaultPolicy.WithMaxRetries 1)
}
```
This will return `None` for any computation that has faulted and `Some` for those that have completed. Expect this to roll out in the latest MBrace.Azure release within the next few days.

**Comment by cgravill** [comment]
Thanks, that looks really useful. We'll give it a go when it's rolled out.

**Comment by eiriktsarpalis** [comment]
The change has been pushed to the latest MBrace.Azure release. Let me know how it works for you. You can use the `Cloud.ProtectedParallel` implementation inside the `MBrace.Core.Library.Protected` namespace.

Also, please make sure that you manually clear your Azure tables before using as some breaking changes have been introduced.

**Comment by cgravill** [comment]
Yes, this works well for us. I've done some small tests and we're able to get other results despite faults I inserted.

We're going to be running some larger experiments so this should be very helpful!

**Comment by eiriktsarpalis** [comment]
Great to hear. Let me know how that works out :+1:

**Comment by eiriktsarpalis** [comment]
Assuming this is resolved. Closing for now.
