### ISSUE TITLE
check that the path to the pubsettings file is valid before we’ve downloaded the cspkg

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#119]
@isaacabraham writes

> One other thing – we don’t check that the path to the pubsettings file is valid until /after/ we’ve downloaded the cspkg. We should do this before. And we should look at caching the cspkgs (even if in the temp folder) rather than continually downloading it every time. Both of these are not critical features but would be nice to have.

**Comment by isaacabraham** [comment]
Fixed by #145.
