### ISSUE TITLE
Invalid connection string pops the entire cluster

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Azure#12]
I know that this is potentially already fixed, but wanted to track the issue here. If you supply an invalid connection string, every node throws an unhandled exception and recycles. Also the process log becomes poisoned and you need to manually clear it out.

**Comment by krontogiannis** [comment]
Hmm, you mean in case of using a slightly different but valid (letter casing) connection string in your client, and then all workers failing with invalid configuration exceptions ('Unregistered resource' etc)?

**Comment by isaacabraham** [comment]
That was the behaviour I've seen, yes. Basically I was appending ; at the end of the connection string.

**Comment by krontogiannis** [comment]
Ok cool, that was fixed in [8ae4241](https://github.com/mbraceproject/MBrace.Azure/commit/8ae424120aae98638bf86852e9fe2aa8a1729090). All strings in Configuration are normalized before calculating the Configuration hash.

**Comment by isaacabraham** [comment]
Cool - what's the expected behaviour if you pass in a bad connection string?

**Comment by krontogiannis** [comment]
The service.Start method is going to [fail](https://github.com/mbraceproject/MBrace.Azure/blob/master/src/MBrace.Azure.Runtime/Service.fs#L151).
I believe it's a responsibility of the person writing the worker role code to catch this and stop the worker role. (I'm going to add this in the [WorkerRole sample](https://github.com/mbraceproject/MBrace.Azure/tree/master/samples/MBrace.Azure.CloudService.WorkerRole)).

**Comment by isaacabraham** [comment]
Sorry - I mean on client side. So assume that the cluster is created successfully; someone then calls Runtime.GetHandle(config) where the storage connection string is invalid. What does the caller see - and when do they see it - immediately on GetHandle() or only when they call something that communicates to the cluster proper?

**Comment by krontogiannis** [comment]
Oh, client side GetHandle will fail if any of the 2 connection strings are invalid. Although I believe i should wrap this exception on a custom InvalidConfiguration or sth :)
