### ISSUE TITLE
Standalone MBraceAzure.exe

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Azure#129]
We should create a standalone executable which could be run outside of a cloud service. This would allow you to run on e.g. a raw VM, or through a container of sorts.

Thoughts?

**Comment by eiriktsarpalis** [comment]
A standalone worker is already bundled with the `MBrace.Azure` nuget package. It can be found in the `tools` folder. It's also used when calling the `cluster.AttachLocalWorker()` method from the client.

**Comment by isaacabraham** [comment]
Ah, perfect.
