### ISSUE TITLE
Too many storage containers created by MBrace

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Azure#13]
I think this should be more like the hadoop way of storing stuff, which although not perfect is better - the current version creates a new container for every single process that you create which quickly becomes unwieldly. A better approach IMHO would be a folder inside a single container that is supplied at config time, under which MBrace owns and can do what it wants with.

**Comment by dsyme** [comment]
+1

**Comment by krontogiannis** [comment]
The problem with storing state in one single container and table for all processes is when you want clear all resources for a process, you will need to delete everything manually instead of deleting just a container and a table.

IMO the best practice should be to create a temporary storage account for your cluster (with pre process containers/tables etc) and have registered your own storage account for your cloudfiles. And when you are done with your cluster just delete it.

**Comment by isaacabraham** [comment]
I see where you're coming from - that would be the easiest from a maintenance point of view. However storage accounts are expensive resources in terms of Azure - you only get 20 of them per subscription, unless you jump through hoops to get the limit increased; this won't scale particularly well. I think you should seriously consider multi tenanting on a storage account - the cluster should have a well-known set of tables, queues and container(s) based on e.g. some arbitrary ID e.g. MBraceStatusTable_1234 or something that could be cleaned up through e.g. a script or similar e.g. Powershell cmdlets etc..

**Comment by dsyme** [comment]
I'm thinking about the phrase "when you are done with your cluster" :)

In very large Hadoop-like data systems, clusters (or at least their storage, their schema, their logging and reporting mechanisms, and the ability to get compute VMs data-local to the storage) hang around forever: they become a shared system that is permanently around, processing endless jobs, and running some reactively in real-time. 

Perhaps that view will change to have some of these resources be more transient. But I suspect MBrace does have to be on a trajectory to be able to run a cluster+data efficiently for 2-5 years, with software upgrades etc. over the course of that lifetime?

**Comment by isaacabraham** [comment]
That's true. Although Azure (with things like ADF) and others (including ourselves) are heavily pushing the idea - at least for batch processing - that clusters can (should?) be run on commodity hardware that can be torn down without storing any valuable data on it.

But yes, once you see the ease of use of going from the repl directly to the cluster, I do myself start to think of my mbrace clusters as just an always-on grid-compute-esque model. It's a really expensive way to run though unless you know that you have enough work to make it cost effective.

**Comment by eiriktsarpalis** [comment]
@isaacabraham one of the nice things about mbrace-on-azure is that computation state is largely independent from worker instances. You could practically delete the cluster with processes running, then re-provision a few days later and watch computations resume from where they left off. I can imagine the Brisk panel offering options for real-time scaling or even pausing the cluster altogether.

**Comment by isaacabraham** [comment]
@eiriktsarpalis Yep, I like that idea. We'd probably have to add the ability to "wipe" a cluster state e.g. blob / table / queue / service bus etc. though as a fallback though, as well as offering the ability to "retain" the cluster state (basically, provision the service bus + storage account separately).
