### ISSUE TITLE
Can't provision cluster: ForbiddenError: The server failed to authenticate the request.

### ISSUE THREAD

**Issue by evilpepperman** [mbraceproject/MBrace.Azure#130]
Using latest released code (MBrace 1.0.0 / MBrace.Azure 1.1.3).
`AzureCluster.fsx` was edited to point to my publishing credentials file and fix the region.
Running StarterKit: `0-provision-azure-cluster.fsx`:

    let deployment = Config.ProvisionCluster()

causes

> Hyak.Common.CloudException: ForbiddenError: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.
   at Microsoft.WindowsAzure.Management.LocationOperations.<ListAsync>d__0.MoveNext()
>    at MBrace.Core.Internals.AsyncExtensions.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in C:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Utils\AsyncExtensions.fs:line 101
   at MBrace.Azure.Management.Extensions.Deployment.Provision.Static(String publishSettingsFile, Region region, Int32 vmCount, FSharpOption`1 vmSize, FSharpOption`1 cloudServicePackage, FSharpOption`1 subscriptionId, FSharpOption`1 logger, FSharpOption`1 logLevel, FSharpOption`1 mbraceVersion, FSharpOption`1 storageAccount, FSharpOption`1 serviceBusAccount, FSharpOption`1 serviceName, FSharpOption`1 serviceLabel, FSharpOption`1 enableDiagnostics) in C:\Users\eirik\Development\mbrace\MBrace.Azure\src\MBrace.Azure.Management\Extensions.fs:line 60
   at <StartupCode$FSI_0009>.$FSI_0009.main@() in C:\dev3\ScratchPad\AMC-lab\MBrace.StarterKit-1.0\MBrace.StarterKit-master\HandsOnTutorial\0-provision-azure-cluster.fsx:line 73
Stopped due to error

Notes:

1. I have been able to provision clusters before, but now I can't.
2. I have tried multiple newly created publishing credentials files.
3. All searches for this pathology only direct to Azure PowerShell cache cleaning.  Is there a cache to fix for MBrace?

**Comment by eiriktsarpalis** [comment]
Strange.

Could you try following the tutorial in `200-managing-azure-clusters.fsx` (under the `going-further` folder) and see if it also fails there? If it does, using the `manager` object defined in line `63`, can you verify whether either of the following commands complete successfully?
```fsharp
manager.ShowDeployments()
manager.Storage.ShowAccounts()
```

Also, have you tried using a different Azure subscription?

**Comment by evilpepperman** [comment]
Tried your reco.  Same response as before for each:

    let deployment = manager.Provision(serviceName = "mbracetest", vmCount = 4, vmSize = VMSize.A3)
    manager.ShowDeployments()
    manager.Storage.ShowAccounts()

I used my `Microsoft Azure Enterprise - Cloud Platform` subscription, since that was what was in the pub file.

To try another subscription, I will need to get another account.  I will look into that.

Any caches to clear?  I ask because I know an HTTP 401 challenge success is cached, and the Azure PowerShell issue related to this error message is resolved by clearing local state files.

I'm thinking that mBrace is doing what it should, but Azure may be miffed by the pub file, for some reason.  But I can't find any helpful Azure doc on this, since so much of the publishing seems controlled by Azure PowerShell or Visual Studio.

Would @dsyme have any helpful comments?

**Comment by eiriktsarpalis** [comment]
We simply pass any auth data straight to the Windows.Azure.Management library. I'm unsure whether that makes any use of caching. Could you try following the cache clearing instructions for powershell and see if that helps?

**Comment by evilpepperman** [comment]
I accepted that this is not an MBrace issue, so we can close it.  

I just want to highlight that others may run across this problem.  It seems connected to corporate network management, since I could use the same credentials from a home network.  If I have more details, I'll let you know.

**Comment by evilpepperman** [comment]
This is not an mBrace issue.  I am closing this.

BTW, it should be noted that users behind gateways/firewalls should be sure to white-list the IPs used by Microsoft Azure Management API.  Found here: https://www.microsoft.com/en-us/download/details.aspx?id=41653

If I had known this a month ago...
