### ISSUE TITLE
Check core count before provision / resize

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Azure#135]
If you try to provision a cluster that goes over the core count limit on your subscription, the cluster will silently fail. You get no feedback as to why this happens.

We can either check the number of available cores on the subscription before the provision operation, and / or check the error that comes back from Azure if this fails - unless MAML hides this, it *should* return an error stating that core count has been exceeded.

This is probably a common cause of provisioning failures as the default limit per subscription is 20 cores - so just 5 * Large or 2 * Extra Large.

**Comment by eiriktsarpalis** [comment]
Is there a way that we can check the remaining core allowance through Azure.Management?

**Comment by isaacabraham** [comment]
I haven't looked through the MAML library. But even if it isn't we can just call the raw Azure HTTP endpoint for this - I've done it before, it's a simple call IIRC.

**Comment by isaacabraham** [comment]
OK. The reason we're not seeing this is because we're using ```BeginCreateAsync()``` rather than ```CreateAsync()```. The former simply does a fire-and-forget, the latter actually waits until the request has been validated and accepted by Azure before returning. We can either: -

a) Go back to using ```CreateAsync()```.
b) Look at polling using ```GetOperationStatus()``` to continually check the status of the request.

**Comment by isaacabraham** [comment]
Fixed in part (during provisioning) by #141.
