### ISSUE TITLE
Exception when running in a Console application

### ISSUE THREAD

**Issue by vikranthc** [mbraceproject/MBrace.Azure#137]
let task = 
         cloud { return "Hello world!" } 
         |> cluster.Run

When I try to run the above piece code in a console application targeting an azure cluster, I get the following exception.

    System.InvalidOperationException was unhandled
    Message: An unhandled exception of type 'System.InvalidOperationException' occurred in     MBrace.Core.dll
    Additional information: Blob stream has already been committed once.

This works fine in the f# interactive from a .fsx file.

I am on VS2015 using MBrace.Azure (1.1.19) and MBrace.Core (1.0.15). You can find the source code at https://github.com/vikranthc/MbraceExperiment.

Here is the output from the console.
![capture](https://cloud.githubusercontent.com/assets/396989/12573726/a9ca9528-c3b9-11e5-8fd3-521e95fcfc30.PNG)

**Comment by eiriktsarpalis** [comment]
I can reproduce this. Interesting bug.

**Comment by swoodhouse** [comment]
I'm getting the same bug in my own code, also VS2015, MBrace.Azure 1.1.19 and MBrace.Core 1.0.15.

**Comment by palladin** [comment]
One interesting observation is that if I remove this https://github.com/mbraceproject/MBrace.Azure/blob/master/src/MBrace.Azure/Utilities/BlobValue.fs#L87
line everything seems to work!

**Comment by eiriktsarpalis** [comment]
Fixed as of MBrace.Azure v1.1.20. Please update your nuget packages.
