### ISSUE TITLE
High rate of management operations

### ISSUE THREAD

**Issue by Rurouni** [mbraceproject/MBrace.Azure#139]
Hi folks,  

What should be the normal calling pattern from MBrace worker role to ServiceBus around management operations(like GetSubscription or SubscriptionExists)? 
I am asking this because when we were running quite big cluster (200 instances) we got warning from azure people that we are doing high amount management operations for mbrace servicebus to the extent that they needed to throttle us... 
I have also noticed that subscribtion list on topic:mbraceworkeritemqueuev1 was 573 vmhost like names in there(whilst my bigger cluster ever was 200) and even if I deleted all subscriptions manually it was enough to deploy 1 Mbrace woker role and all 573 subscriptions on the topic were recreated...

Cheers

**Comment by isaacabraham** [comment]
Those management operations are only called AFAIK when a cluster is created, that's it. They should also have no relation to cluster size AFAIK - need to confirm.

Did the Azure team tell you what operations you were doing? I know that there can be high-ish volume of service bus messages for things like keep-alive pings from a node - if you can find out the API calls that are being made then we can track it back.

State of the cluster is stored in more than just service bus, it's also in table storage. I suggest ```Resetting()``` the cluster and removing everything (or removing the storage entities manually) to remove any dirty state left over.

**Comment by eiriktsarpalis** [comment]
Interesting. I've pushed a [commit](https://github.com/mbraceproject/MBrace.Azure/commit/3ff3768c75e209ffb8f77dedcd160b29fe7cac2f) that addresses this issue. However, I'd be interested to know the type of application you're using mbrace with. This behaviour should only occur in scenaria where deaths of worker instances are unusually common.

**Comment by dsyme** [comment]
Looking at "total requests" on the serice bus it looks like my 4 machine cluster is making 484 requests per 5 minutes, even when not in use (from a couple of weeks ago, I left it running - bad boy). 139020 per day.  Seems too many...

**Comment by Rurouni** [comment]
That's except from my communication with them:
> Based on our monitoring data we were getting management calls about ~2000 per second and the message volume is less than 200 per second.  Can you please identify all the code paths that execute GetSubscription or SubscriptionExists? When GetSubscription is called it also has to fetch the accurate message count as of that time and we have to hit all the back ends involved. It is a very expensive call in terms of resources.
> We are throttling these calls and throw server busy exceptions. Have you received server busy exceptions? We recommend a 10 second back off for server busy exceptions.

I have scanned through codebase and one place looks like the one that  can do the job was:
```F#
    member this.GetMessageCountAsync() = async {
        let! (descr : SubscriptionDescription) = clusterId.ServiceBusAccount.NamespaceManager.GetSubscriptionAsync(clusterId.WorkItemTopic, targetWorkerId.Id) |> Async.AwaitTaskCorrect
        return descr.MessageCount
    }
```

**Comment by eiriktsarpalis** [comment]
Please try MBrace.Azure v1.1.22 and see if the problem still persists.

**Comment by Rurouni** [comment]
@eiriktsarpalis 
I am using mbrace as distributed load test runner, effectively the pattern is: push to every instance one long running job. I am recreating cluster quite often, also I wouldn't be surprised if high network/CPU utilisation are rendering some instance looking as dead (but most of the time I hasn't seen them having CPU > 30%)

Cheers, I will try v1.1.22

**Comment by dsyme** [comment]
> I am using mbrace as distributed load test runner

@Rurouni Great to hear! Could you add a testimonial on http://mbrace.io please?  Anything would be great, just edit here and submit PR:  https://github.com/mbraceproject/mbrace-docs/blob/master/docs/files/index.html#L715

**Comment by palladin** [comment]
@Rurouni The reason that you are seeing so many (573) subscriptions is probably that each time you recreate a cluster you don't call cluster.Reset.

**Comment by isaacabraham** [comment]
@Rurouni just to elaborate on what @palladin is saying - a cluster in MBrace Azure terms is a combination of Cloud Service roles, a couple of service bus queues, and a storage account which contains blobs for both MBrace specific-data (Vagabond stuff + cloud values) and potentially your own data, plus a set of Tables that maintain logs and cluster state.

If you kill a cluster simply by killing the Cloud Service, or even that + the service bus, if you reuse the same storage account as previous clusters then the previous state will get continued with. On one hand this is nice - you can kill the cloud service and recreate it weeks later and the service bus and storage will carry on - but on the other hand if you want to create a "brand new cluster" you need to be cautious of removing everything.

**Comment by Rurouni** [comment]
@isaacabraham and @palladin 
That makes total sense now, I was thinking before that Reset is for situations where cluster stuck in some bad state, so I have probably accumulated several weeks of redeploying cluster every day without reset until issue grown big enough to hit azure scale radars...
Just to be sure, if you just scale out/in topology of the same cluster, do you need to Reset cluster or not?

@dsyme I am definitely up for testimonial, I will try to grab approval for it

**Comment by palladin** [comment]
@Rurouni cluster.Reset is in general a disrupting operation but you can use it as hygienic procedure (cluster state cleanup) between deployments of new clusters.

**Comment by isaacabraham** [comment]
@Rurouni There's a newer version that's been released (1.1.23) which has done some work to minimise these management calls - can you see if that helps?

**Comment by Rurouni** [comment]
Thank you @isaacabraham I will try. It will be some time before I will run cluster of that scale again, and the issue was exaggerated by me not resetting cluster, so it's probably worth closing that issue, as I won't have updates for it for some time...

**Comment by isaacabraham** [comment]
Thanks. If you do spin up a large cluster like that again, let us know the results :-)
