### ISSUE TITLE
Extra Large VM not available in generated packages?

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Azure#140]
Looking at the packages that we're generating and making available in GitHub releases, it appears like we no longer generate ExtraLarge / A4. I thought that we used to - is this intentional or accidental? A4 is a good VM size for MBrace workloads as not only does it have a decent amount of memory and CPU but also gets better network throughput than A3s.

**Comment by eiriktsarpalis** [comment]
Looks like we never did. Looks like an omission in the build script.

**Comment by isaacabraham** [comment]
Do we still have a static member for A3/A4? If so - we should either remove them, as (I believe) trying to deploy an "A4" package will fail (there is no such package) or we should deploy them as well. Or write some redirection code that goes from A3 -> Large etc. at the point of doing the download.

**Comment by eiriktsarpalis** [comment]
@isaacabraham it's just an alias to "ExtraLarge" so it should work

**Comment by isaacabraham** [comment]
Ah ok great.
