### ISSUE TITLE
How is high avialability achieved?

### ISSUE THREAD

**Issue by slav** [mbraceproject/MBrace.Azure#149]
Hello. Is there any documentation on how high availability is achieved?

What happens when server goes offline? What if job doesn't get a chance to finish? Is it restarted on another server or has to wait for the server to come back online?

What if job never finishes? Is there a timeout to report and restart?

**Comment by palladin** [comment]
You can find all the available documentation here http://mbrace.io/programming-model.html
and more specifically about your questions here http://mbrace.io/starterkit/HandsOnTutorial/10-exceptions-and-fault-tolerance.html

**Comment by isaacabraham** [comment]
@slav short answer is that a lot of this stuff is delegated to the provider. So on Azure, messaging is done via Service Bus which is a resilient and fault tolerant message bus. You can place a cloud computation on the bus with no cluster, bring a cluster up a week later on that service bus and storage account it will happily automatically execute the computation.

**Comment by slav** [comment]
Thank you. I've read article on exceptions and fault tolerance and reading through programming model, however, I'm wondering how the system handles things behind the curtain? Is there coordinator?

What if role or worker host crashed and keeps crashing and not coming back or there's constant stream of storage exceptions. Would the work be offloaded to another node?

Under extreme circumstances I've seen role going down for 20-30 minutes before it's recovered. Can mBrace handle this gracefully and use other nodes? If so, how is it doing that?

How is work assigned to a specific role? On a client? Once assigned, can it be moved?

**Comment by isaacabraham** [comment]
Work items are by default sent to any available worker in a round-robin style - basically they all compete for work items from Service Bus. As far as I'm aware, If a node fails a work item, it will go back onto the bus and be picked up by another node. This is just the standard SB mechanism, rather than anything MBrace specific.

**Comment by slav** [comment]
I didn't realize work items are put into Service Bus and then worker roles consume work from it. Is this architecture documented somewhere?

**Comment by isaacabraham** [comment]
@slav This is a common pattern for scale out workloads - put a message on a queue with many competing consumers.

e.g. https://msdn.microsoft.com/en-us/library/dn568101.aspx?f=255&MSPPError=-2147217396

**Comment by slav** [comment]
@isaacabraham I know it's one of the patterns. I didn't know that's what MBrace used. I'm trying to understand how MBrace is using Azure facilities. I'd like to understand how is work sent to role, how does reply happen, how are blob files handled, etc. to understand limitations, what can go wrong, how to foresee it and so on.

**Comment by isaacabraham** [comment]
OK, understood. Maybe put a list of questions here and we can use this as a basis for a (simple) architecture document on MBrace.Azure. But essentially: -

1. When a work item is dispatched, dependencies are serialized and placed in blobs. The work item metadata contains enough details for the worker to access those dependencies and rehydrate them.

2. All work items are resilient as they rely on Service Bus. If a work item does not return, it will be dispatched on the queue for another node to pick it up. Number of retries and duration for a work item are limited only by service bus restrictions.

3. Reply happens - and @eiriktsarpalis can correct me here - by querying the state of a work item. Work Item state in MBrace Azure is managed through Azure Table Storage.

4. Blob files are handled through the CloudFile abstraction - but essentially this delegates to the standard Azure Blob Storage SDK.

5. A Cloud Service role is used for MBrace workers themselves. This enabled dynamic scaling as well based on CPU or queue length.

That's it really - storage for state and dependencies, service bus for resilient messaging and cloud services for compute. We're also looking at removing service bus and just using Storage Queues for the messaging component which will shrink the stack down and allow MBrace.Azure to run entirely locally using the Storage and Compute emulators. I need to get my ass in gear to complete this though...

One area that isn't necessarily built for resiliency is PersistedCloudFlow - if a node goes down, you'll lose that partition of data (for the in-memory version for sure; for blob-backed cloud flows I still don't think it's possible to reshard the partition later on - @eiriktsarpalis again over to you here).

**Comment by slav** [comment]
Thank you. It's hard to come up with all questions ahead of time, usually they happen during discussion. I appreciate you taking the time to share this all. So, the questions:

1. Is there a naming strategy for naming blobs for work and CloudFile? Are old blobs deleted at some point? Or are left forever as garbage?
2. Does worker role update lease on the message it's working on? What if work takes a while to process? Is there any chance another role will pick up the work because lease on the message expired?
3. Can the work time out (take too long to process)?
4. If I understand correctly, result isn't saved anywhere? So, if work is completed and I don't grab it and role crashes result would be lost?
5. What is the mechanism to grab work? I understand role grabs work item from queue. But how does the role decide it's ready for more work or that it's too busy to get more work?

**Comment by eiriktsarpalis** [comment]
@slav regarding your questions:

1. There are two types of blobs being generated by mbrace: (i) internal cluster data such as persisted continuations, assembly dependencies and job results and (ii) blobs created by the user. Runtime and user blobs are usually kept in separate containers. Runtime blobs are typically created using guids and eventually removed if no longer needed. User blobs can use any permitted name and must be removed manually by the user, pretty much like using the underlying Azure blob API.
2. It will keep updating the lease as long as the work item keeps running. Released/expired leases will eventually be dequeued by another instance if available.
3. No, but cloud processes can take a `CloudCancellationToken` as argument. These are effectively the same as `System.Threading.CancellationToken` but with a distributed scope. Computations that take too long can be cancelled remotely. Note that just like F# async, cancellation is cooperative so certain restrictions apply.
4. Results are persisted to blob storage and can always be retrieved using the corresponding `CloudProcess` handle.
5. As it is, each worker dequeues up to a given maximum number of concurrent work items. This can be configured on each worker instance.

**Comment by isaacabraham** [comment]
@slav just to add to @eiriktsarpalis there - you almost certainly wouldn't want the cluster to take responsibility for cleaning up user-data. You might have existing data or want the output from an MBrace job to be used downstream in another application.

**Comment by slav** [comment]
Thank you so much for taking the time to answer. This has clarified a lot.
