### ISSUE TITLE
Add Stop/Update functionality in Service.

### ISSUE THREAD

**Issue by krontogiannis** [mbraceproject/MBrace.Azure#2]
Currently MBrace.Azure.Runtime.[Service](https://github.com/mbraceproject/MBrace.Azure/blob/master/src/MBrace.Azure.Runtime/Service.fs) can only be Started.
Add functionality like: 
* Service.Stop(waitForPendingTasks : bool)
* Service.Update(config : Configuration)

**Comment by dsyme** [comment]
When using the demos, I've felt the need for a "TotalReset()" too, which will just flush all queues, kill all processes etc.  I've found myself trying to do things like this:

    [ for p in cluster.GetProcesses() -> p.Kill() ]

That said, obviously you've got to get worker/process/task control really smooth so this sort of thing isn't needed.

**Comment by krontogiannis** [comment]
Hello, the MBrace version on Brisk is quite outdated. 

Client on master branch supports
runtime.[ClearAllProcesses](https://github.com/mbraceproject/MBrace.Azure/blob/master/src/MBrace.Azure.Client/Client.fs#L182) (although ignores running processes).

You can also force a flush on all runtime related resources using Configuration.[DeleteResources](https://github.com/mbraceproject/MBrace.Azure/blob/master/src/MBrace.Azure.Runtime.Common/Config.fs#L166).

**Comment by dsyme** [comment]
Ok, thanks!  Great to know some of these things are being looked after

Isaac from Elastacloud mentioned to me in person last night that one of the things you're looking at together is to allow people to select which version of the MBrace runtime to have on the cluster - so I could choose MBrace vN.N.N.N, or even MBrace vLatest. That would be fantastic to have in the pipe.

It will also be good to see the upgrade story will be to move an existing cluster from MBrace vN to vN+1 fleshed out, I guess you'll be looking at that with Elastacloud?

**Comment by krontogiannis** [comment]
Sure. At the moment Brisk uses a fairly old version for preview purposes. When we'll be releasing MBrace.Azure as Nuget packages it should be easy for Elastacloud to allow people to select the corresponding  nuget versions.

In regards to upgrading from cluster vN to v(N+1), it's a thing we've been talking about the last days. I think we should open a new issue to talk about that.

**Comment by krontogiannis** [comment]
Fixed in 226faab5a97a948dfd5298fa0d3abc26f26440b2
