### ISSUE TITLE
Discussion thread: MBrace.Azure.Standalone has fixed version dependencies

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Azure#20]
The current approach of bundling up all dependencies in the tools folder is a very nice solution insofar as it's simple to use. However, it then ties up all dependencies to specific versions, meaning that upgrades to dependencies e.g. Azure SDK etc. are difficult (if not impossible) to manage.

Perhaps a hybrid approach whereby you have the dependencies that you control in the tools folder, others as dependencies on the nuget package, and a helper .fsx file that does the searching?

**Comment by eiriktsarpalis** [comment]
The client library is still available in the MBrace.Azure package. Perhaps
MBrace.Azure.Client should have been named MBrace.Azure.Tools or something.

On Saturday, February 28, 2015, Isaac Abraham <notifications@github.com>
wrote:

> The current approach of bundling up all dependencies in the tools folder
> is a very nice solution insofar as it's simple to use. However, it then
> ties up all dependencies to specific versions, meaning that upgrades to
> dependencies e.g. Azure SDK etc. are difficult (if not impossible) to
> manage.
>
> Perhaps a hybrid approach whereby you have the dependencies that you
> control in the tools folder, others as dependencies on the nuget package,
> and a helper .fsx file that does the searching?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbraceproject/MBrace.Azure/issues/20>.
>


-- 
Sent from Gmail Mobile

**Comment by isaacabraham** [comment]
Could (should?) there be a dedicated client package - or would that be essentially the same as the "full" package?

**Comment by eiriktsarpalis** [comment]
Not entirely sure about that. We used to have a dedicated client package
with the old MBrace, but that was since the runtime itself carried so much
extra stuff. Given that the current Azure runtime is just a few
class libraries to be consumed by worker roles, the distinction doesn't
seem so pronounced. Essentially we pushed two packages containing identical
software, one for development and one quick consumption over fsi. We're
open to suggestions on how this could be imrpoved.

On Saturday, February 28, 2015, Isaac Abraham <notifications@github.com>
wrote:

> Could (should?) there be a dedicated client package - or would that be
> essentially the same as the "full" package?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbraceproject/MBrace.Azure/issues/20#issuecomment-76540166>
> .
>


-- 
Sent from Gmail Mobile

**Comment by isaacabraham** [comment]
I'm not sure I have a great answer - the fsx approach is more flexible but requires package dependencies and so on (plus probably support for both nuget and paket). The tools approach is very easy to consume - you just need to be aware that you might need to do out-of-band releases of this package incase of a bug in a downstream dependency, that's all.

**Comment by dsyme** [comment]
Closing this.  MBrace.Azure now includes a "tools" directory, but AFAIK you can also just depend on the package.  It seems likely that in some situations upgrading to a later package may require a matching upgrade to the MBrace.Azure being used by workers or addition of binding redirects.
