### ISSUE TITLE
CloudFile.WriteAllLines fails if file already exists

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#21]
I'm using the elastacloud preview

This gives an exception. I'm pretty sure this used to succeed. Either way I think it should succeed.

```
cloud { 
    let! _ = CloudFile.WriteAllLines([""], path = "test/tmp.txt")
    let! _ = CloudFile.WriteAllLines([""], path = "test/tmp.txt")
    return ()
} |> cluster.Run
```

Exception:

```
System.IO.IOException: The file 'text/tmp.txt' already exists in store.
   at <StartupCode$MBrace-Runtime-Core>.$FileStoreCache.MBrace-Store-ICloudFileStore-Write@97-3.Invoke(Tuple`2 _arg7) in c:\Users\eirik\Development\nessos\MBrace.Core\src\MBrace.Runtime.Core\Store\FileStoreCache.fs:line 97
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@787-1.Invoke(a a)
--- End of stack trace from previous location where exception was thrown ---
   at <StartupCode$MBrace-Azure-Client>.$Process.AwaitResultAsync@115-1.Invoke(Result`1 _arg2) in c:\Users\eirik\Development\nessos\MBrace.Azure\src\MBrace.Azure.Client\Process.fs:line 115
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@797-1.Invoke(a a)
   at MBrace.Continuation.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in c:\Users\eirik\Development\nessos\MBrace.Core\src\MBrace.Core\Continuation\ExceptionDispatchInfo.fs:line 136
   at <StartupCode$MBrace-Azure-Client>.$Client.RunAsync@186-2.Invoke(Unit unitVar) in c:\Users\eirik\Development\nessos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 186
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@813.Invoke(AsyncParams`1 args)
   at MBrace.Continuation.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in c:\Users\eirik\Development\nessos\MBrace.Core\src\MBrace.Core\Continuation\ExceptionDispatchInfo.fs:line 136
   at <StartupCode$FSI_0379>.$FSI_0379.main@()
Stopped due to error
```

**Comment by dsyme** [comment]
Updated with correct repro

**Comment by krontogiannis** [comment]
Hmm, that exception is thrown by the worker's filesystem cache. I believe the problem is that CloudFile is considered an immutable primitive and will be cached on workers. So creating a CloudFile with the same name is mutation and that's a problem with caching.

If we want to support this, one simple solution, I think, is to change the `ICloudFileStore` interface and add a `GetChecksum(path)` method that each cache can use. Not sure if this can be supported by all stores though.

**Comment by eiriktsarpalis** [comment]
@krontogiannis should it be possible to overwrite an existing cloud file unless it has been deleted first?

**Comment by dsyme** [comment]
Same applies to WriteAllText, WriteAllBytes

**Comment by dsyme** [comment]
@krontogiannis But you support a "Delete", which must presumably be coherent w.r.t. caching, so in sample code I've just been using

                do! cloud { try do! CloudFile.Delete(path) with _ -> () }
                let! cloudFile =  CloudFile.WriteAllBytes (data,path) 

Couldn't the operations be defined like this?

**Comment by krontogiannis** [comment]
@eiriktsarpalis  I don't believe this is the issue here. If a cloudfile is cached in nodeA and nodeB, and it's updated (or deleted and created again) in nodeA, then all reads in nodeB will return the old, cached value.

That's why I think that a checksum might be handy.

**Comment by krontogiannis** [comment]
I had opened an issue for this in the old runtime [#1](https://github.com/mbraceproject/MBrace.Legacy/issues/1).

**Comment by palladin** [comment]
I think it is a difficult problem... If you can delete by name you need to maintain cache coherence across the cluster. Or you can treat the CloudFile as a volatile resource and the single source of truth is the blob storage.

**Comment by dsyme** [comment]
(As an aside, I just ran an operation like this where a write of a very large file appeared not to have succeeded.  I may have been imagining things though, I'll try to find a proper repro, this is just to mention it)

```
// First connect to the cluster
let cluster = Runtime.GetHandle(config)

// Create a directory in the cloud file system
let dp = cluster.DefaultStoreClient.FileStore.Directory.Create("perf-files")

let timeSizes sizes f = 
 [ for sz in sizes do 
    printfn "starting size %d" sz
    let job = 
        cloud {
          let! res = f sz
          return res
        }
        |> cluster.CreateProcess 
    printfn "awaiting result for size %d" sz
    let res = job.AwaitResult() 
    printfn "size %d took %fs" sz job.ExecutionTime.TotalSeconds
    yield (sz, job.ExecutionTime.TotalSeconds), res ]
    |> List.unzip


let bytesWritePerf, bigCloudByteFiles = 
    timeSizes [ 1; 10; 100; 1000 ] <| fun sz -> 
        cloud { let data = [| for i in 0 .. sz * 1024 * 1024 -> byte i |] 
                // This delete is needed because of https://github.com/mbraceproject/MBrace.Azure/issues/21
                do! cloud { try do! CloudFile.Delete(path=dp.Path + sprintf "/big-bytes-%d" sz) with _ -> () }
                return! CloudFile.WriteAllBytes (data,path=dp.Path + sprintf "/big-bytes-%d" sz)  }
```

However after running it the first time, the file "big-bytes-1000" didn't exist, though the overall operation succeeded. I fear the write operation for the 1GB (= 1000) file failed in some way, or the delete took precedence over the write. The second time I ran it the 1GB file appeared.

I haven't confirmed a repro for this as yet.

Don

**Comment by dsyme** [comment]
How about a type distinction ``ImmutableCloudFile`` v. ``CloudFile``?

**Comment by dsyme** [comment]
BTW on this topic CloudRef sounds a bit like it is mutable to me (due to Ref = mutable in F#. I know the "Ref" means "serializable reference" but you don't use "Ref" for all the other serializable types like CloudVector).   

But then the question of consistent naming for Immutable v. volatile comes up.  ImmutableCloudValue is a bit long. Perhaps immutable type names should be 
* CloudValue, CloudVector, CloudFile

and volatile
* UpdateableCloudValue, UpdateableCloudVector, UpdateableCloudFile

though the latter are a bit long.  Maybe you don't plan to have them at all.

**Comment by palladin** [comment]
If think that the problem is the combination of (naming things) + (ability to delete by name) if you have both you have effectively mutability and you need to pay attention to cache coherence.

**Comment by palladin** [comment]
I think that @azurecoder's idea of using Azure Cache is brilliant. It is the most economical and easy to implement solution for the issue of cache coherence.

**Comment by krontogiannis** [comment]
Isn't Azure Cache an in-memory cache? CloudFile's are not cached in memory.
Also Azure Cache is specific to MBrace.Azure but the CloudFile problem is not Azure specific.

**Comment by palladin** [comment]
Azure Cache is a distributed cache with a local in-memory component. We can use the capabilities of Azure Cache to have a global Cache Coherence protocol. Of course we need to re-architect so the problem of local-file caching is delegated to the runtime.

**Comment by azurecoder** [comment]
One of the things I'd like to see in MBrace is the storage hierarchy. This is one feature of Spark which makes it versatile across so many scenarios. I believe MBrace can implement the same ideal with a hierarchy of memory, then disk/storage. Azure Cache is great for MBrace because (in Azure at least) you get Spark-like functionality without the overhead of the memory management. Spark has to allocate memory to both the JVM and the cache which in lot of cases needs tuning to avoid spill over or running out of JVM heap. Pushing this onto Azure sidesteps all of these problems and will give MBrace users a much better experience.

**Comment by dsyme** [comment]
This discussion seems old and there have been considerable changes in the CloudFile API
