### ISSUE TITLE
Discussion thread: CloudFile perf

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#24]
I've been playing with CloudFiles checking out current perf using Azure storage. I know this is work in progress, just wanted to get a feeling for where we are, and to open a discussion about how to set expectations correctly and where future work may be done.

Here's the script I've been using with timings shown using my local-redundant storage on a 2 machine (small-instance?) cluster (presumably machine size doesn't matter much).  1, 10, 100, 1000 refer to MB, results are in seconds.  Lots of caveats: some results may be heavily affected by caching, and all results may be affected by other activity on the VMs and in the data centre as a whole, and the storage options on the storage account etc. etc.

I assume the overall level of I/O perf is far from competitive with dedicated map/reduce systems that have direct access to disks (and schedulers which place work directly on the right partition), but would be reasonably competitive with other systems based on Azure storage. Comparisons with AWS would be interesting too.

I'd like to understand the data-locality model better - is it possible to request that processes run close to data, or is caching of immutable data the technique being relied on to get data perf?

You definitely notice the affects of caching with occasional results like this (8s --> 1s)
```
// #1 [(1, 0.3036431); (10, 0.397323); (100, 8.2052502)]
// #2   [(1, 0.3057246); (10, 0.3347746); (100, 1.7994133)]
```

```
#load "credentials.fsx"

open MBrace
open MBrace.Azure
open MBrace.Azure.Client
open MBrace.Azure.Runtime
open MBrace.Streams
open MBrace.Workflows
open Nessos.Streams

(**
 This script tests cloud file perf
 
 Before running, edit credentials.fsx to enter your connection strings.
**)

// First connect to the cluster
let cluster = Runtime.GetHandle(config)

// Create a directory in the cloud file system
let dp = cluster.DefaultStoreClient.FileStore.Directory.Create("perf-files")

//--------------------------------------------------------------------
// Stress test some data storage

let timeSizes sizes f = 
 [ for sz in sizes do 
    printfn "starting size %d" sz
    let job = 
        cloud {
          let! res = f sz
          return res
        }
        |> cluster.CreateProcess 
    printfn "awaiting result for size %d" sz
    let res = job.AwaitResult() 
    printfn "size %d took %fs" sz job.ExecutionTime.TotalSeconds
    yield (sz, job.ExecutionTime.TotalSeconds), res ]
    |> List.unzip



//  #1 [(1, 1.0114461); (10, 1.2006469); (100, 3.8053827)]
//  #2 [(1, 1.0706926); (10, 1.3171087); (100, 3.9861948)]
let lineWritePerf, bigCloudTextFiles = 
    timeSizes [ 1; 10; 100 ] <| fun sz -> 
        cloud { let lines = [| for i in 0 .. 10000 * sz-> "Some text that takes about one hundred bytes to store in default encoding if you look you can check" |] 
                // This delete is needed because of https://github.com/mbraceproject/MBrace.Azure/issues/21
                do! cloud { try do! CloudFile.Delete(path=dp.Path + sprintf "/big-lines-%d" sz) with _ -> () }
                return! CloudFile.WriteAllLines(lines,path=dp.Path + sprintf "/big-lines-%d" sz)  }

// #1 [(1, 0.6813008); (10, 1.200415); (100, 6.4491432)]
// #2 [(1, 1.133324); (10, 1.5016807); (100, 6.7401698)]
let textWritePerf, _ = 
    timeSizes [ 1; 10; 100 ] <| fun sz -> 
        cloud { let text = System.String(' ', sz * 1024 * 1024)
                // This delete is needed because of https://github.com/mbraceproject/MBrace.Azure/issues/21
                do! cloud { try do! CloudFile.Delete(path=dp.Path + sprintf "/big-text-%d" sz) with _ -> () }
                return! CloudFile.WriteAllText(text,path=dp.Path + sprintf "/big-text-%d" sz)  }

// #1   [(1, 0.5426625); (10, 2.0498235); (100, 21.1039728)]
// #2   [(1, 0.8444004); (10, 1.9827996); (100, 21.1224367)]
// #3   [(1, 0.6401685); (10, 1.8751011); (100, 16.3687715); (1000, 219.2221633)]
let bytesWritePerf, bigCloudByteFiles = 
    timeSizes [ 1; 10; 100; 1000 ] <| fun sz -> 
        cloud { let data = [| for i in 0 .. sz * 1024 * 1024 -> byte i |] 
                // This delete is needed because of https://github.com/mbraceproject/MBrace.Azure/issues/21
                do! cloud { try do! CloudFile.Delete(path=dp.Path + sprintf "/big-bytes-%d" sz) with _ -> () }
                let! cloudFile =  CloudFile.WriteAllBytes (data,path=dp.Path + sprintf "/big-bytes-%d" sz) 
                return cloudFile }

// #1   [(1, 3.1591611); (10, 0.5312207); (100, 3.0732776)]
// #2   [(1, 0.2813198); (10, 0.4259485); (100, 2.6784925)]
// #3   [(1, 0.8718545); (10, 1.1114111); (100, 2.6215714)]
let lineReadPerf, lineReadResults = 
    timeSizes [ 1; 10; 100 ] <| fun sz -> 
        cloud { let cloudFile =  CloudFile(dp.Path + sprintf "/big-lines-%d" sz) 
                let! lines =  CloudFile.ReadAllLines(cloudFile)   
                return lines.Length }

// #1 [(1, 0.3036431); (10, 0.397323); (100, 8.2052502)]
// #2   [(1, 0.3057246); (10, 0.3347746); (100, 1.7994133)]
// #3   [(1, 0.302497); (10, 0.3630366); (100, 1.8345874)]
// =  approx 100MB/sec
let textReadPerf, textReadResults = 
    timeSizes [ 1; 10; 100 ] <| fun sz -> 
        cloud { let cloudFile =  CloudFile(dp.Path + sprintf "/big-text-%d" sz) 
                let! text =  CloudFile.ReadAllText(cloudFile)   
                return text.Length }


// #1 -   [(1, 0.3307201); (10, 0.5625038); (100, 5.9124926)]
// #2 -   [(1, 0.367018); (10, 0.5394005); (100, 0.7989355)]
// #3 -   [(1, 0.3044898); (10, 0.3846313); (100, 1.1439518)]
// #4 -   [(1, 0.3003568); (10, 0.3778789); (100, 0.8314062); (1000, 7.9186146)]
let bytesReadPerf, bytesReadResults = 
    timeSizes [ 1; 10; 100; 1000 ] <| fun sz -> 
        cloud { let cloudFile = CloudFile(dp.Path + sprintf "/big-bytes-%d" sz)
                let! bytes =  CloudFile.ReadAllBytes(cloudFile)   
                return bytes.Length }

```

**Comment by palladin** [comment]
One interesting observation is that the HDInsight (Azure's Hadoop as a service) offers a decoupled model between storage and computation. So, the model "bring the computation closer to the data" is not in general applicable and it would be interesting to test the read/write throughput of HDInsight and MBrace on Azure.

**Comment by dsyme** [comment]
My understanding is that HDInsight may have some kind of backdoor available to storage, to give storage locality, though I don't know any details.  I assume it would be specific to that service.

**Comment by palladin** [comment]
Don, check this http://dennyglee.com/2013/03/18/why-use-blob-storage-with-hdinsight-on-azure/ especially the "Data locality?" section.

**Comment by azurecoder** [comment]
HDInsight uses wasb an HDFS proxy protocol. It's hugely fast and performant but it was used initially mainly because Azure didn't support SSD on VMs. This has been rectified now leading to fast HDFS giving two potential models. Wasb uses the block writes that we've been discussing Nick so that nodes can read (and write) input and output concurrently. It's a good model. We know it back to front and can help replicate in F# I'm sure. Personally I think you should you define an HDFS-like file system which can be applied to azure storage and/or san storage/disk at the lowest level. .NET needs less reliance on an open source Java stack and more on its own.  

The decoupling of compute and data is great for enterprise since Azure storage contains the final post calculation output. AWS and S3 doesn't take that tack, copying data to and from S3 since the guarantees are not on S3 (they are to an extent on Azure Storage ~ 20000 IOPS) and data is copied too and from S3 to HDFS from transient clusters.

**Comment by isaacabraham** [comment]
Premium Azure Storage perhaps is also an option (albeit an expensive one).

**Comment by dsyme** [comment]
OK, so it sounds like there's no specific MBrace.Azure issue here, but the question is more an orthogonal systems issue that's related to your Azure assets.

**Comment by isaacabraham** [comment]
Yes and no. Azure Storage has upper limits in terms of IO e.g. as @azurecoder mentioned 20K IOPS. There are ways around this e.g. sharding data across storage accounts etc.. The value add of MBrace.Azure will be to mitigate against hitting those limits as best as possible through caching and e.g. eager read-aheads of data. Data locality is also important, so putting your data and compute in the same data centre is important (Brisk guarantees this) - as well as to reduce your costs!

I suspect one issue that we see now in terms of performance is that cloud streams cannot currently shard a single file over multiple workers, which is something that Hadoop offers. Once this is into MBrace we'll see much better throughout for single files.

**Comment by dsyme** [comment]
Closing this since it's an old discussion
