### ISSUE TITLE
CloudSequence.New taking forever to complete with large inputs

### ISSUE THREAD

**Issue by eiriktsarpalis** [mbraceproject/MBrace.Azure#26]
When writing about 80MB of integers

This is possibly related to e9341abbe16bebb4919f82fedb8248338ec799fd

**Comment by eiriktsarpalis** [comment]
I can confirm that serializing to a temp file before copying to blob storage sped things up. This should be probably taken into consideration the Azure.Store implementation.

**Comment by krontogiannis** [comment]
The fix in e9341abbe16bebb4919f82fedb8248338ec799fd was about blobs created by the runtime, not user.

I believe using a temp file before uploading should not be a part of Azure.Store implementation.
In case your are using caching the cloudseq would be written two times locally?

So, is the cloudsequence created in the runtime or using the local client?

**Comment by krontogiannis** [comment]
I suppose it is an issue when using the client (client does not use a local cache). If that's the case I'll enable caching in client, but a [CacheBehavior](https://github.com/mbraceproject/MBrace.Core/blob/master/src/MBrace.Runtime.Core/Store/FileStoreCache.fs) like OnWriteAndDiscard/OnReadAndDiscard or sth that would delete the cached file after its uploaded would be useful.

**Comment by eiriktsarpalis** [comment]
I don't think this should be conflated with caching. This is an implementation-specific bug that happens to appear when caching is not being used. Effectively, it makes uploads of large files impossible from the client side.

**Comment by krontogiannis** [comment]
Well that seems to be the default OpenWrite's [behavior](http://toolheaven.net/post/Azure-and-blob-write-performance.aspx).

If I add this in the Azure.Store:
* When using cache, the blob would be copied *twice* (both in read and write, although the performance problem is mostly on the Write case).
* Should `BeginRead`, fetch the entire file from blob, copy it and return a *FileStream*, not a BlodStream?
* Should `Write` method's stream be also a *FileStream* that on dispose does the filesystem <-> azure copying?

I feel like the fix should be done in Azure.Client and Azure.Store should just expose the azure BlobStream when implementing our interface.
