### ISSUE TITLE
Allow caching of dependencies on nodes (or storage)

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Azure#30]
Whilst the automatic assembly generation through Vagabond, and subsequent transport to cluster nodes is easy to use and lightweight, it would be good to have an opportunity to improve efficiency by e.g. uploading dependent assemblies into a well-known location e.g. blob storage. Or the ability to tell a cluster something like "cache this assembly" (or even a nuget package). The assembly could be loaded onto the cluster; when the local client comes to package code to send to the cluster, it would then only package up the remaining code that wasn't cached on the cluster already.

No idea what the effort to do this is, but it could improve the whole round-trip performance.

**Comment by eiriktsarpalis** [comment]
AFAIK this is how assemblies are currently uploaded to the cluster. There did exist a bug however which would result in assemblies erroneously being uploaded every time to the blob storage. This has been fixed as of 0.6.1.

**Comment by isaacabraham** [comment]
Awesome. Where do the assemblies live? I'm thinking of us artistically uploading some assemblies as part of a cluster deployment e.g. Fsharp Data etc. to make things even smoother.
________________________________

**Comment by eiriktsarpalis** [comment]
Good idea, although it is not very practical to implement at the moment. We are working on a refactoring of Vagabond-related code which should make this easier to provide.

**Comment by isaacabraham** [comment]
OK. Does Vagabond create a single assembly with all the dependencies sliced together or just ship all dependencies as separate assemblies and then one with the ```cloud { }``` code?

**Comment by eiriktsarpalis** [comment]
It computes all assemblies on which `cloud { }` code transitively depends. How these assemblies are shipped and stored is up to runtime implementation. Currently MBrace.Azure saves its assemblies to store by pickling the [AssemblyPackage](http://nessos.github.io/Vagabond/reference/nessos-vagabond-assemblypackage.html) record. This should be changed so that the assembly binaries are saved as standalone files.

**Comment by isaacabraham** [comment]
Yes - that would allow more opportunities for optimizing what gets sent into Azure.

**Comment by eiriktsarpalis** [comment]
I wouldn't worry about that too much though. Assemblies are generally speaking small files. What concerns me most is REPL session data, which can really degrade the experience if too large.

**Comment by dsyme** [comment]
I think increasing the observability of what's being sent is a good first step. For example, logging could show 

    sending 200MB from static values Matrix1, Matrix2, EnormousString (wlll be amortized on workers)
    sending 5KB from InteractiveFragment.dll (wlll be amortized on workers)
    sending 47MB from EntityFramework.dll (wlll be amortized on workers)

In the 1:1 sessions I've been doing I notice myself teaching people not to "send whole file to interactive" (which can redefine large chunks of static data, if there are any) but just send what's needed incrementally.

**Comment by isaacabraham** [comment]
+1 - it's always best practice in my experience to execute scripts incrementally anyway.

**Comment by eiriktsarpalis** [comment]
I'm investigating ways of using cecil to statically infer what static data is being referenced by each piece of uploaded code. If this works out, it should be possible to upload dependencies on an on-demand basis, rather than the current naive dump of the entire session state.

**Comment by isaacabraham** [comment]
++++++1

**Comment by dsyme** [comment]
FWIW I'm personally generally happy with the current behaviour - at least, I understand it.  The static-data dependency graph would be an added bonus I suppose.

I'm doing lots of 1:1 demos with people at the moment and some may turn into regular users. I'll keep an eye on whether other people understand the model.

**Comment by dsyme** [comment]
Closing this as the discussion seems to have come to a conclusion with no specific bug?
