### ISSUE TITLE
Tag versions?

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#33]
Would it be possible to tag released versions in the Git history please? When you [bump the version](https://github.com/mbraceproject/MBrace.Azure/commit/603034d93560096aab9211076e5253a200135e32), does that correspond to a release? 

Thanks
Don

**Comment by eiriktsarpalis** [comment]
Sure, do you think it would appropriate for prereleases?

**Comment by dsyme** [comment]
Yes, I think it's worth it for any version picked up by Brisk or pushed to nuget

**Comment by eiriktsarpalis** [comment]
Ok, I just tagged the latest nuget release.

https://github.com/mbraceproject/MBrace.Azure/releases/tag/v0.6.1

**Comment by dsyme** [comment]
thanks!
