### ISSUE TITLE
Using MBrace.Azure.Client package from a project

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#37]
The DLLs for the MBrace.Azure.Client nuget package are all under "tools".  Should these be under "lib/net45" so that they are automatically added as references when referring to the MBrace.Azure.Client package from a .NET project?

(I presume it is valid to use MBrace.Azure.Client from a /NET project. In this specific case, I'm using it from an F# WebAPI project, as I want the web API requests to submit work to the cluster)

**Comment by eiriktsarpalis** [comment]
The MBrace.Azure package does this. MBrace.Azure.Client contains essentially the same libraries but repackaged with their dependencies in the tools folder for easier loading from fsi. Come to think of it, it should probably be renamed to something like MBrace.Azure.Repl.

**Comment by krontogiannis** [comment]
I believe the purpose of the MBrace.Azure.Client package is just for consumption from FSI. The MBrace.Azure package is identical and should be used from either runtime or client projects. 

There is also a discussion for this as #20

**Comment by dsyme** [comment]
Closing this since it is marked as duplicate
