### ISSUE TITLE
GetProcess and Kill on a rogue process can be really slow

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#4]
I created a process with zillions of parallel cloud tasks by mistake. 

       5b729a7db6784dc191f645b14beede23    Running  False      00:14:16.8437768    1 /   1 /   0 /   2  string []            20/02/2015 12:24:23 +00:00  N/A                        
 
I try 

    let p = cluster.GetProcess("5b729a7db6784dc191f645b14beede23")
    p.Kill()
     
However both steps took a *very* *long* time, and killing didn’t seem to work, as a subsequent GetProcesses reveals this:

       5b729a7db6784dc191f645b14beede23  Cancelling  False      00:31:40.0118744    1 /   1 /   0 /   2  string []            20/02/2015 12:24:23 +00:00  N/A                        

I don't know specifically what's going on, but stress-testing this sort of job control problem is super-important.

**Comment by dsyme** [comment]
(This is an "experience report" than a "bug report", so please feel free to just close it, once the feedback has been noted)

**Comment by dsyme** [comment]
As another example of creating a rouge job.  This one is interesting w.r.t. stress-testing cancellation because this one involves serializing 320MB of floating-point data to the cluster, which is probably a bit much since I'm working over WiFi....  So getting it to cancel fast is useful!

    #load @"packages/MathNet.Numerics.FSharp/MathNet.Numerics.fsx"
    
    open MathNet.Numerics
    open MathNet.Numerics.LinearAlgebra

    let inputs = [ for i in 1 .. 1000 -> Matrix<double>.Build.Random(200,200) ]

    [ for m in inputs -> cloud { return m.Inverse() } ]
    |> Cloud.Parallel
    |> cluster.Run

**Comment by dsyme** [comment]
BTW I'd love to see more operational data in the ShowProcess view.  For example, 

- MB transferred
- %time in data serialization
- %memory utilization 

or hook into the existing .NET mechanisms for reporting some of these things.

**Comment by palladin** [comment]
Thanks Don, we will look into this.

**Comment by isaacabraham** [comment]
+1 more operational data. Network utilisation as well. It would be useful for seeing how much time is taken between IO and actual computation.

**Comment by dsyme** [comment]
Somewhat related - I think I would use a "cluster.TrialRun(cloudWorkflow)" which showed how much data and code would be sent down the wire (and did any other sanity checks possible).

**Comment by eiriktsarpalis** [comment]
There exists a `RunLocal : Cloud<'T> -> 'T` method which executes a workflow on the local threadpool. Perhaps it could be augmented in a way that counts the number of closures that would be sent for remote execution.

**Comment by dsyme** [comment]
Hi all,

Using the latest Brisk+mbrace, I got a couple of rogue processes that never got killed successfully.  These resulted in 25% CPU utilization overnight, even though I sent the kill request:

                  762b9f9451a44ad88bcdbdb824794043  Kill requested  False      18:27:03.9987303      0 /   0 /   0 /   1  float []                                  01/03/2015 14:32:09 +00:00  N/A                        
                  98384871fe5646bb8afb0000860d1e14  Kill requested  False      18:26:57.0616338      0 /   0 /   0 /   1  float []                                  01/03/2015 14:32:16 +00:00  N/A                        

What's the cancellation model used, so I might understand?  Rebooting the instances seemed to clear things out (in the sense that the jobs didn't restart), but the processes are still labelled as "Kill requested".

**Comment by krontogiannis** [comment]
Hi,

so 'Kill requested' is equivalent to 'Running' with the difference that the `Cancel` method of process' `CancellationToken` has been called. A process becomes 'Killed' when the cancellation continuation of the root task is called or 'Completed' when any of the other two continuations is called.

I'm doing some work [here](https://github.com/krontogiannis/MBrace.Azure/tree/bugfix/process-state) for issues related to process state (like staying 'Running' or 'Posted', etc).

Can you post the code?

**Comment by dsyme** [comment]
The processes were 200x200 matrix inversions posted using the code [here](https://github.com/elastacloud/mbrace-on-brisk-starter/blob/master/src/Demos/6-nuget-packages.fsx):

It may be that I restarted the workers mid-process, see also https://github.com/elastacloud/mbrace-on-brisk-starter/issues/35#issuecomment-76708102, where scaling down the size of the cluster from 10 to 2 seemed to leave a number of jobs listed as "Running" for ever.

**Comment by dsyme** [comment]
I'm closing this out since there is no specific repro
