### ISSUE TITLE
Nuget Package incompatible with Latest Service Bus Version

### ISSUE THREAD

**Issue by drcrook1** [mbraceproject/MBrace.Azure#40]
Latest Service Bus is 2.6.0, mBrace package is looking to use 2.5.2

Repro steps:
Install latest Microsoft.Service Bus as well as latest Microsoft Service Bus Processor Host
Install MBrace.Azure.Client

**Comment by krontogiannis** [comment]
Thanks, we will upgrade it to the latest package.

**Comment by drcrook1** [comment]
Can you let me know as soon as its done?

 

I have a presentation in Philly on MBrace for real time analytics and detecting leaks in pipelines and well obviously it doesn’t work yet :)

 

Also, your nugget package definitions all specify specific version, can you switch to specifying min versions acceptable or version ranges?

 

Thanks,

~David

**Comment by krontogiannis** [comment]
@drcrook1 Sure. I've upgraded MBrace.Azure to the latest `Microsoft.ServiceBus 2.6.2` in 368502733e7dfcbce8d5ca1fe3a04ae95c26e818. We can probably upload a new package tomorrow with a min version `2.5.2`

**Comment by eiriktsarpalis** [comment]
@krontogiannis Continuing from #42, I just noticed that the [MBrace.Azure](https://www.nuget.org/packages/MBrace.Azure) explicitly lists all transitive dependencies from the `WindowsAzure.*` packages. Is this intentional? I think this may lead to problems.

**Comment by krontogiannis** [comment]
No, this should be removed. Only MBrace.Core, FsPickler, Vagabond/WindowsAzure.ServiceBus and WindowsAzure.Storage should be top level dependencies.

**Comment by drcrook1** [comment]
Hi Guys,

 

On this thread,  I’m getting issues in my solution for locating things like Queues.fs and tables.fs and serialization.fs I’m not sure what that is about.  I’ve bypassed all of the nugget stuff for now by using assembly redirects and explicitly referencing the assemblies via fully qualified paths (obviously will only ever work on my box, but at least its getting closer).  Im guessing the queues.fs and tables.fs and such is a result of missing something…?

 

Thanks for taking a look at this.  I would highly suggest prioritizing using mbrace in a compiled form, as that is how most people I work with would want to interact with it, as a component in an integrated architecture.

 

Let me know how it goes.  I can detect my cluster now, but still running into issues with running jobs on it (reasons above).

 

Thanks,

~David

**Comment by dsyme** [comment]
Just to note that a revert was made back to ServiceBus 2.5.2 in [this commit](https://github.com/mbraceproject/MBrace.Azure/commit/0036e06d0594e84fe0be7d68d82c27c81328d033).  I'm not sure what the problem was that caused the revert

**Comment by dsyme** [comment]
I'm closing this since it is old and  MBrace.Azure is now on ServiceBus.Azure 2.5.4.
