### ISSUE TITLE
MBrace.Azure induces too many dependencies on the client-side

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#42]
As things currently stand, using MBrace.Azure on the client side induces a _lot_ of dependencies, e.g. see #40 for one ramification of this.  

I know this has been discussed elsewhere, but this will become more and more of a problem as we attempt to locate MBrace client functionality in various real-world settings where MBrace is integrated as part of a bigger solution. In #40, the problem situation was integrating the MBrace client into another Azure cloud service.  

Similarly, I also experimented with putting the MBrace client in an Azure website. It worked, but the large set of dependencies makes this inherently risky/difficult for more complex websites and also makes MBrace feel like a heavy technology on the client side - when it shouldn't really feel like this.  This is particularly a shame when most of what you want to do from a client is relatively simple - you want to specify code to run and call "cluster.CreateProcess".

The homogeneity of MBrace is one of its advantages, but reducing the set of induced client dependencies seems really important.  

Is there any way we could take a different approach for the MBrace Azure client side and decouple the MBrace.Azure client from most transitive dependencies?  Or indeed decouple the client and server dependency sets altogether (by "facading" the MBrace client programming model and ensuring appropriate remapping on deserialization?)

(Note that to take the decoupling to its logical conclusion, we eventually consider exposing an MBrace server/worker as a REST API that accepts a limited range of inputs including queries - ShowLogs() etc. - and even code in an appropriate pickled format.  But for now I'm just suggesting ways that we can reduce the induced dependency set and reduce the degree of tight coupling).

**Comment by isaacabraham** [comment]
A quick fix might be simply to remove the direct bundling of dependencies into libs and make them proper NuGet dependencies.

**Comment by eiriktsarpalis** [comment]
I'm not sure this is a possibility given the current design of the cluster. Excluding the core and FsPickler/Vagabond, all other dependencies are introduced on account of the Azure Storage and Service bus libraries. Currently, these are essential to client code, since this is how we communicate with the cluster. Even if we could somehow reengineer the cluster to remove these dependencies, the client would most likely lose its capacity to directly interface with the store, a feature that I find to be critical.

That said, I just noticed that [MBrace.Azure](https://www.nuget.org/packages/MBrace.Azure) incorrectly lists all transitive `WindowsAzure.*` dependencies. I will have this fixed for the next release.

**Comment by palladin** [comment]
If the problem is the Microsoft/Windows.Azure.* dependencies ... we can probably program directly to the Azure REST APIs (of course it will need a lot of work).

**Comment by isaacabraham** [comment]
@palladin: A *lot* of work. There's lots of stuff in the Azure SDKs that are abstracted away from you when doing blob / table stuff. I considered doing it for the Azure Storage Type Provider (and would love to). You have to manage auth token generation, batching, request / response parsing etc.. It's not something to be undertaken lightly.

**Comment by isaacabraham** [comment]
@eiriktsarpalis: can you elaborate on this? The HTTP option that @dsyme has suggested might be doable - albeit it'd mean rather than the client going directly to storage / tables for querying the cluster, you went to the cluster itself. This is an approach that other cluster solutions use e.g. HDP / HDI exposes Templeton, which is a set of HTTP APIs that allow you to query the cluster etc.

Secondly - the NuGet package not only lists the transitive dependencies, but it lists them as ```=``` i.e. fixed dependencies - they really should be ```>=``` i.e. "minimum of".

**Comment by palladin** [comment]
@isaacabraham Thanks for the confirmation.

**Comment by eiriktsarpalis** [comment]
@isaacabraham Yes, I guess that could work. But this probably means that you would need to have at least one worker running in order to enqueue a process or even upload a large dataset to store. This is not currently a requirement.

By the way, I think that it makes sense to have an abstract client type to be implemented by all runtimes. This would help consolidate the MBrace API across runtimes/proxies and facilitate testing.

**Comment by krontogiannis** [comment]
Are we talking about fully replacing `MBrace.Azure.Client` or just having an lightweight client (just Vagabond, no Storage/ServiceBus) that works over HTTP as an alternative?
If the second one is the case, that lightweight client could expose:
* Simple queries like GetLogs/GetWorkers/metrics etc
* Possibly a `Create/Post/Publish/UploadProcess` or sth that would pack the workflow and dependencies in a zip and upload them to the `MBrace.Server`

TBH having full client over http where you could do all sorts of stuff like `cluster.StoreClient` and similar seems like an overkill to me.

Also what about authentication?

**Comment by dsyme** [comment]
Stepping back a bit, what I really want to discuss is deploying MBrace as part of a production solution. 

Right now that means deploying MBrace.Azure.Client into an F#/C# project - this might implement a Web Job, Web Site, Worker Role or even a Windows client application. Let's call these "Client Hosts". Client hosts and MBrace.Azure.Client aren't going away and I didn't really mean to suggest they should.

It's worth noting that these client hosts are in many ways the logical equivalent of Hadoop head nodes, which publish a range of both command-line and web/HTTP access points.  MBrace doesn't come with a pre-baked implementation of a head node.  In some ways that is a good thing but we should also be aware that it places some burden on the user.

I think it might help if we gave some standard templates/samples for the different kinds of client hosts we expect to be used in practice for MBrace.Azure  - for example, we could give a sample project for a Web Job (which uses MBrace.Azure.Client, user code and a backing cluster, and publishes one or more HTTP endpoints)

Cheers
Don

**Comment by isaacabraham** [comment]
A "lack of" a head node is something that Richard and myself have discussed several times over the past few weeks. In some ways I find not having one a nicer mental model to deal with - it's just a grid compute model - plus you don't need something like zookeeper and supervisor to manage head node with failovers.

On the other hand some things like you mention aren't currently available - this is something that we would probably end up building into Brisk at some point a la Templeton; Richard comes from a Spark background (as I'm sure the @eiriktsarpalis and the guys are aware from our discussions so far!) and often talks to me about things like how Spark is able to generate DAGs when calculating complex queries, and how a head node which has an understanding of the rest of the cluster is essential for this sort of thing. Whether that's the case or not I don't have an opinion on :-)

**Comment by eiriktsarpalis** [comment]
@dsyme I think the naming of the `MBrace.Azure.Client` package is unfortunate, and the source of confusion. Its contents are identical to `MBrace.Azure` but packaged with all dependencies in the tools folder for easier loading by F# interactive, as FAKE is. We should probably rename this to `MBrace.Azure.Repl` or something.

**Comment by dsyme** [comment]
Yes, in this discussion when I said ``MBrace.Azure.Client`` I actually meant ``MBrace.Azure`` used in a client host.

Agreed that ``MBrace.Azure.Client`` really needs to be renamed, I suggest ``MBrace.Azure.Client.Scripting``.  Equally it would be great if you just didn't need to have this package and could instead include a single loader script in ``MBrace.Azure``

**Comment by dsyme** [comment]
For completeness, I should mention that several examples of host clients are here https://github.com/mbraceproject/MBrace.Azure/tree/master/samples

We don't yet have any documentation for these on any of the primary learning paths, which is one reason why I hadn't encountered them.  I'll add some to mbrace-docs

**Comment by dsyme** [comment]
(Oh, how do those samples relate to these: https://github.com/mbraceproject/MBrace.Demos/tree/master/azure ??  Which ones are canonical?)

**Comment by eiriktsarpalis** [comment]
I think we should focus on MBrace.Demos, we shouldn't make new users dig into the MBrace.Azure source code for samples.

**Comment by krontogiannis** [comment]
Yeah any samples should be added in MBrace.Demos. Anything in MBrace.Azure/samples should be just for development or in case you want to use the latest bits in a worker role or other host.

**Comment by dsyme** [comment]
Closing this as the discussion has come to an end - the MBrace.Azure.Standalone package has solved this for now.  It still feels like there are too many client-side dependencies when an MBrace client is in a compiled program, but perhaps the refactoring that's going on will help this.
