### ISSUE TITLE
SImplfication of the API.

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Azure#44]
The starter pack demos are a great way to get up and running.

**However!** There are currently a number of top-level modules for computations that do similar (or the same) thing (albeit perhaps with different behaviour / performance characteristics). A good example of this is ```Cloud.Parallel``` and ```DivideAndConquer.Map```. The former takes a ```Cloud 'R array``` and executes it in parallel. A common pattern is to go from ```'T Array``` to ```Cloud 'R Array``` vai ```Array.map``` and then ```Cloud.Parallel```. The latter takes a collection of ```'T``` and a ```'T -> Cloud 'R``` and executes it in parallel.

The standard pattern seems to be to use ```Cloud.Parallel```. Why have two? The latter seems to be a more efficient way of doing things as it bundles up jobs into single jobs etc. which is a good thing. But then you end up with two modules doing similar things.

I would suggest that at some point before 1.0, a review should be made of the common tasks etc. involving cloud computations; these could be put together into a top-level module in a very basic manner - just the 80% of things that the beginner and average user will want to see, in order to increase the pit of success and reduce going down blind alleys or leading to initial confusion. The remaining should be put into a set of sub-namespaces e.g. ```.Advanced.``` or similar.

**Comment by eiriktsarpalis** [comment]
Good point, there is already a discussion on this matter [here](https://github.com/mbraceproject/MBrace.Core/issues/18). I'm going to close this since it is really an MBrace.Core issue.

**Comment by isaacabraham** [comment]
Cheers - sorry for the duplication.
