### ISSUE TITLE
GetProcesses?

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#46]
There is a ``ClearAllProcesses`` and ``ShowProcesses`` but no ``GetProcesses`` on the Runtime object.  Should you be able to get the list of all process programmatically?

**Comment by eiriktsarpalis** [comment]
I think we used to have this in the old runtime, should be added.

**Comment by dsyme** [comment]
Yes, I noticed it in the old tutorials, that's the reason I'm mentioning it (I haven't needed it)

**Comment by krontogiannis** [comment]
Yeah, I had this deliberately removed (and just kept `GetProcess(pid)` for a single process) because of some performance reasons. I will re-enable this as soon as I add some memoization loggic on the client.

**Comment by krontogiannis** [comment]
Added in 62605f9142651f6380841b85a35aff8643009aec.
