### ISSUE TITLE
Proposal: provision azure instances when running unit tests from AppVeyor

### ISSUE THREAD

**Issue by eiriktsarpalis** [mbraceproject/MBrace.Azure#48]
Currently, CI builds run by AppVeyor do not include any cluster unit tests. This is because CPU capacity of the provided build servers is insufficient for hosting local standalone clusters. Perhaps this could be solved by somehow provisioning worker instances to Azure on every build. Not sure if this is technically feasible but I think it's worth investigating.

**Comment by dsyme** [comment]
I suspect this doesn't quite seem feasible due to provisioning times.  Closing as it's not on a critical path.
