### ISSUE TITLE
Cleaning up process data

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#5]
I'm playing around with the Elastacloud preview of MBrace clusters in Azure.

I'm not sure what the cleanup/retention policy is for process data, but I'm seeing lots of blobs here:

![cppp](https://cloud.githubusercontent.com/assets/7204669/6314638/77fd35c2-b9de-11e4-8322-396649f6c596.PNG)

**Comment by krontogiannis** [comment]
Process specific data (blobs and tables with the 'process' prefix) is not automatically deleted after completion.

Current API supports cleanup using the
```fsharp
    runtime.ClearProcess(pid) 
    runtime.ClearAllProcesses(pid) 
```
methods.

I think the Brisk bits do not support this, instead you need do sth like
```fsharp
    runtime.GetProcess(pid).ClearProcessResources()
```
