### ISSUE TITLE
Cluster gets created but workers are invisible

### ISSUE THREAD

**Issue by mathias-brandewinder** [mbraceproject/MBrace.Azure#50]
Using https://github.com/elastacloud/mbrace-on-brisk-starter/tree/ddb8071f3556f688ef7eacae33dcc08915da08d6 
I create a cluster via Brisk, I see 2 worker instances running.
Running 1-hello-world-fsx:
let cluster = Runtime.GetHandle(config) works fine
cluster.ShowWorkers() : nothing shows up

**Comment by dsyme** [comment]
Have you entered your configuration strings correctly, i.e. do they match the config strings shown in Brisk for the cluster exactly?  (If you entered one of the to point to a different storage account or service bus then I think you can get the result you're seeing)

**Comment by mathias-brandewinder** [comment]
Copying the strings from Brisk, nothing looks off there.

**Comment by dsyme** [comment]
Hmmmm.... I just tried a new cluster and a fresh sync of that repo and the workers appeared ok.

Random ideas:

* Check the instances in azure management console. If they say "Running", then try rebooting them (though I don't know of any particular reason why that would help)

* start over from scratch and check again?  (I presume you've already just done that - I.e you had a fresh cluster and fresh starter pack already)

**Comment by krontogiannis** [comment]
* Like Don said, check from the azure portal if the workers are indeed running.
* What's the output of the following commands
    * `cluster.ShowWorkers(timespan = TimeSpan.FromDays 42., showInactive = true)`
    * `cluster.ShowLogs()`

**Comment by mathias-brandewinder** [comment]
2 instances of the workers are running. I'll send you the results of the detailed ShowWorkers / ShowLogs later. BTW my next step will be to nuke all the contents of the storage account. Is it helpful to you if I keep a copy? I have deleted and re-created clusters a couple of times, under different names, but every time I observe the same issue.

**Comment by mathias-brandewinder** [comment]
Well, just tried it again today, and the problem seems to have resolved itself - started a fresh cluster, and this time everything is running just fine. Not sure what happened, but can't reproduce anymore, so I'll close it.

**Comment by dsyme** [comment]
Good to know.  Perhaps Isaac should check the Brisk logs to see if there was a failure.
