### ISSUE TITLE
Client side runtime failing to initialise with 'ParallelOperationThreadCount' is larger than maximum of '64'

### ISSUE THREAD

**Issue by Rurouni** [mbraceproject/MBrace.Azure#55]
Happens on machines with >16 cores because of such code in MBrace.Azure.Runtime\Common\Config.fs:`client.DefaultRequestOptions.ParallelOperationThreadCount <- (System.Nullable(4 * System.Environment.ProcessorCount))`

**Comment by krontogiannis** [comment]
Thanks! Fixed in b7cd208d18a068e5edbb7cbbc40716d9f2eaedc2.
