### ISSUE TITLE
Integration with FSharp.Azure.StorageTypeProvider

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#56]
The FSharp.Azure.StorageTypeProvider is awesome.  Let's document the integration of the type provider with MBrace and consider what it may mean for the design of the data primitives.

The blob storage provider integrates inn a fairly simple way:

```
type Account = AzureTypeProvider<"mbracestorage1","29PA09R+...g==">

let textAsyncWorkflowJob = 
  cloud {
    let! text = Account.Containers.mbraceuserdata00000.``mvqcvqsa.qry``.ReadAsStringAsync() |> Cloud.OfAsync
    return text
  }    |> cluster.CreateProcess
```
For the table type provider the selected tables should be usable as partitioned data sources to the CloudFlow data model.   Here's what a query of a table looks like today:
```
open FSharp.Azure.StorageTypeProvider.Table
Account.Tables.MBraceUserData00000.Query().``Where Partition Key Is``.``Equal To``("SomeKey").Execute() 
```

This returns an array of items - that could be adjusted to return an object that fits with the CloudFlow model, or it could return an ``IEnumerable<T>``.

**Comment by krontogiannis** [comment]
Yeah the this is awesome. Although, it feel's a bit odd that we have to fetch in memory the entire partition and then pass it to CloudFlow.

**Comment by eiriktsarpalis** [comment]
A few thoughts:
* There could be an AzureProvider.MBrace library that provides common extensions, for example `.ReadAsStringCloud`.
* An interesting aspect of this library is that it permits access to storage accounts independent of cluster configurations. MBrace on its own does not support this yet.
* MBrace.Core uses an interface for store operations, ICloudFileStore. It would be interesting to investigate if a type provider could be built on top of that. Imagine a type provider capable of listing CloudCells and CloudSequences.

**Comment by dsyme** [comment]
Closing for now since it's a somewhat old discussion
