### ISSUE TITLE
Process.AwaitResult is completing and throwing OperationCanceled exception prematurely

### ISSUE THREAD

**Issue by Rurouni** [mbraceproject/MBrace.Azure#58]
When parallel cloud flow executes heavy Network IO(https) against some external service and external service is struggling to reply (as in using mbrace for load/stress testing)
then somewhere in the middle of the flow execution(sometimes even after several minutes of running)  Process.Completed becomes true still showing that there is some amount(>0) of ActiveJobs and Process.AwaitResult throws OperationCanceled exception
Nothing in WAD logs collected on Verbose level (with Mbrace logging to Trace) shows any exceptions just usual logs

Enviroment:
Self-provisioned azure cluster
built from sources with last commit being https://github.com/mbraceproject/MBrace.Azure/commit/66bbae198965cc7309919664a5701e4da9a2385c

**Comment by eiriktsarpalis** [comment]
Could you ensure that `OperationCanceledException` is not originating from user code? In other words does the same problem happen when you wrap your local code in `try Async.Start userCode with _ -> ()` ?

**Comment by Rurouni** [comment]
It appeared that this exception is thrown by Async.Parallel in the end..never thought it can throw it when all child tasks are catching their exceptions.. but same logic using Task.WhenAll is not throwing OperationCanceled...anyway, my bad,  it's not an mbrace issue
