### ISSUE TITLE
Problem using from VS2015

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#61]
I know we've discussed this already, but is there any easy way to make MBrace clusters usable when the client is running an FSharp.Core 4.4.0.0 - for example F# Interactive in VS2015?

We accidentally opened the hands-on tutorial in VS2015 today and got an error about FSHarp.Core 4.4.0.0 (things worked correctly when we used in VS2013)

thanks
don

**Comment by eiriktsarpalis** [comment]
The easy way would be to hand-deploy the cluster using the starter kit from inside VS 2015, making sure that the correct FSharp.Core binding redirects are set for the worker role.

But this doesn't scale, particularly when working with brisk. It is reasonable to expect jobs from clients of different versions during the lifetime of a cluster. Given that user code is already being executed in isolated AppDomains, perhaps it would make sense to load different versions of FSharp.Core in each of them. Every job AppDomain would have to define its own set of binding redirects, which I'm not even sure is technically possible.

**Comment by dsyme** [comment]
You may be able to use this for the binding redirect policy of an app domain

    https://msdn.microsoft.com/en-us/library/system.appdomainsetup.configurationfile(v=vs.110).aspx

Really the binding redirect policy of the client should be used I suppose.

You could also manage binding redirects yourself using an assembly Resolve event.

**Comment by dsyme** [comment]
@eiriktsarpalis I've improved the documentation on the website about the need to provision explicitly when using Visual Studio 2015 clients, see http://www.m-brace.net/#contribute

> Given that user code is already being executed in isolated AppDomains, perhaps it would make sense to load different versions of FSharp.Core in each of them. Every job AppDomain would have to define its own set of binding redirects, which I'm not even sure is technically possible.

If this is possible it would be fantastic and may go a long way to helping at least get rid of the FSharp.Core dimension of the versioning problem in most cases.

**Comment by dsyme** [comment]
I'll close this for now as it is solved as well as possible given the still major problems with version dependencies described in #53
