### ISSUE TITLE
Negative "Active" count in process summary

### ISSUE THREAD

**Issue by kip9000** [mbraceproject/MBrace.Azure#62]
When viewing the process summaries, we saw this:

       cf4a7393ae404b8ca48c5d527efbe1af  Completed  True       21:07:33.5211889   -1 /   0 /   2 /   1  string * (string * string []) []       01/04/2015 15:38:29 +00:00  02/04/2015 12:46:03 +00:00 

Note the negative count for Active processes.

**Comment by krontogiannis** [comment]
Can you post the output of `cluster.ShowLogs()`

**Comment by dsyme** [comment]
Closing this since the logs were never received
