### ISSUE TITLE
Use of Async<_> v. Cloud<_>

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#7]
In the API for the current ElastaCloud preview of MBrace on Azure, I see that things like

    CloudFile.ReadAllLines

and

    myCloudFile.GetSizeAsync

return type ```Async<_>``` rather than ```Cloud<_>```.  What's the rationale for this? It feels like all the operations which operate in the cloud workflows should always return ```Cloud<_>```?

**Comment by dsyme** [comment]
It took me a while to work out that this is the correct formulation to read the lines of a file:

    cloud { let! lines = cloudFile.Read CloudFile.ReadAllLines |> Cloud.OfAsync
            return lines.Length }

I suppose I expect this to just be:

    cloud { let! lines= cloudFile.ReadAllLines()
            return lines.Length }

**Comment by krontogiannis** [comment]
I think the (MBrace.Core)[https://github.com/mbraceproject/MBrace.Core/] repo is more appropriate for programming model issues.

For common operations like readlines you can use the static methods of the CloudFile class:
```fsharp
CloudFile.ReadAllLines(cfile)
CloudFile.Read(cfile, deserializer)
```
that return Cloud<_>.

Additionally the MBrace.Core 0.9.1 (thats not on Brisk) API uses only Cloud<_> as a return type on all operations and primitives.

**Comment by dsyme** [comment]
OK, great to know this is cleaned up in MBrace.Core 0.9.1. The version currently in the Brisk preview doesn't have CloudFile.ReadAllLines with that return type.  

I'll close this and try to remember to use MBrace.Core for core programming model issues :)

**Comment by eiriktsarpalis** [comment]
@dsyme I have started a related [discussion](https://github.com/mbraceproject/MBrace.Core/issues/9) in MBrace.Core, I would be interested in seeing your feedback.
