### ISSUE TITLE
Workers having jobs assigned indefinitely after Process has completed

### ISSUE THREAD

**Issue by Rurouni** [mbraceproject/MBrace.Azure#75]
Hello,
I am seeing quite strange issue where after Process has successfully completed with no exceptions (in both Process and azure logs) all workers still have 1 job assigned to each of them and the only way out is to restart the cluster. It doesn't happen all the time, but the bigger the cluster is - more chance that it will happen
**Environment**: cluster with 20 workers (manually deployed azure cloud service 0.6.6 MBrace.Azure) with job count limited to only 1 per worker. 
**Scenario**:
Process starts with one cloud flow that will do Cloud.Parallel inside, like below
```F#
cloud {
    let userIds = [|1..totalUsersCount|]
    let workerJob userIds = cloud { 
            return ParallelUserFlow.Run(userFlow, userIds, userArrivalRate/maxJobs, 1).Result
        }
    let concurrentRuns = 
        userIds
        |> Array.splitByPartitionCount maxJobs 
        |> Array.map (fun partition -> workerJob (partition |> Array.map (fun userId -> sprintf "LoadTestUser%d" userId)))
    let! results = Cloud.Parallel concurrentRuns
    return results
}
```

I have counted all "Starting Job" and "Completed job" in azure logs and it was correct amount. No other logs indicating error or abnormal behavior.
One thing that maybe related or not is that Cloud.Parallel is not assigning all jobs immediately, there is usually quite big delay before all jobs are assigned (like assigned 13 jobs immediately and then other 7 after 1 min or so)

**Comment by palladin** [comment]
I have seen also the same issue and it is the same with https://github.com/mbraceproject/MBrace.StarterKit/issues/20
@krontogiannis is investigating the issue.

**Comment by krontogiannis** [comment]
Fixed in https://github.com/mbraceproject/MBrace.Azure/commit/db7640dd2f38a5760c3ce1910916e71d68ffa963

**Comment by Rurouni** [comment]
Thank you guys! Can somebody release new MBrace.Azure package with that fix included please?

**Comment by krontogiannis** [comment]
Released v.0.6.10-alpha.
