### ISSUE TITLE
Cloud.Parallel takes long time to allocate all jobs to all workers

### ISSUE THREAD

**Issue by Rurouni** [mbraceproject/MBrace.Azure#79]
Hello,
I am seeing constant behaviour where Cloud.Parallel does not allocate all jobs to all free workers immediately.On 10 instance cluster it usually allocates some amount(ranging from 3 to 7) almost immediately then after several minutes it will add 1-3 more, than more, eventually allocating all, but it can take up to 6 mins
Like below:
![image](https://cloud.githubusercontent.com/assets/693362/7474873/02f15974-f33c-11e4-8119-241f1bcd5767.png)

Same behaviour occurs if instead of using Cloud.Parallel I will submit 10 processes with 1 job in each

**Comment by palladin** [comment]
Hi @Rurouni,
Is it possible to check the service bus queue length and see if it is in sync with the external visible behaviour.

**Comment by Rurouni** [comment]
I peeked into service bus queue and there was at first 1 message and immediately after there were 10 messages for whole duration of the test in there with  some guid in the body, at the end of the test they all disappeared.
Whilst from worker perspective: there was initially 1 job assigned, completed, spawned another 10 jobs, 7 got assigned immediately, another 1 after 1 min, than another 1 after 2 min, and then at 4 min mark it assigned all of them

![image](https://cloud.githubusercontent.com/assets/693362/7502519/857aa2b2-f434-11e4-8816-6fa3acd31807.png)

**Comment by palladin** [comment]
@Rurouni Thanks for the info! 
@krontogiannis Do you have any possible explanation for this behaviour?

**Comment by krontogiannis** [comment]
@palladin We need to see why some of the workers are idle instead of dequeueing (i quess that the remaining ~3 jobs are not even dequeued or else the counters would've increased).

**Comment by palladin** [comment]
@Rurouni I'm investigating this behaviour and I have some strong suspicions that it is a Service Bus issue. Is it possible the next time you see these weird slowdowns to delete the Service bus queues and topics and try again.

**Comment by isaacabraham** [comment]
@palladin anything to add to this? And @Rurouni are you still seeing this behaviour?

**Comment by palladin** [comment]
@isaacabraham I haven't seen that kind of behaviour for some time now. I think it is safe to close it.

**Comment by Rurouni** [comment]
Job allocation is definitely faster and more reliable for me for quite some time as well

**Comment by isaacabraham** [comment]
Great - let's leave this closed then.
