### ISSUE TITLE
Incorrect storage connection string doesn't generate an error

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Azure#83]
If you use an invalid storage connection string on the client side to attach to a cluster e.g. wrong key, and call ShowWorkers(), you simply get back an empty list in e.g. FSI rather than an error being returned.

**Comment by krontogiannis** [comment]
Hi, do you mean that the connection string itself is wrong, or there is mismatch with the storage used by the cluster?

**Comment by isaacabraham** [comment]
The former - I used an outdated account key. I didn't get back an error, just an empty list of workers. When I corrected the account key the correct workers were returned.

**Comment by krontogiannis** [comment]
I can't reproduce this. Using an outdated account key (after using regenerate at the Azure portal), i get an exception during GetHandle.

```
MBrace.Azure.Runtime.InvalidConfigurationException: Invalid Storage Account Configuration ---> System.AggregateException: One or more errors occurred. ---> Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
```

**Comment by isaacabraham** [comment]
OK - maybe this has been fixed in the latest codebase - I'm still working off the latest nuget packages (0.6.5).

**Comment by mathias-brandewinder** [comment]
I observed a similar problem multiple times, where I would get an empty list of workers, but could still send work to the cluster, which would work just fine. I hadn't thought about the storage connection as a possible cause, I'll check if I can reproduce!
