### ISSUE TITLE
Channel performance

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#86]
I notice some stackoverflow questions on Azure queue performance, e.g. http://stackoverflow.com/questions/12915585/azure-queue-performance, with notes

> For adding 1000 items in table storage it took over 3 minutes, and with the changes I described in my answer it dropped to 4 seconds (250 requests/sec). In the end, table storage and storage queues aren't all that different. The backend is the same, data is simply stored in a different way. And both table storage and queues are exposed through a REST API, so if you improve the way you handle your requests, you'll get a better performance.

> The most important changes:
> * expect100Continue: false
> * useNagleAlgorithm: false (you're already doing this)
> * Parallel requests combined with connectionManagement/maxconnection 

Can these improvements be applied to MBrace's implementation that maps MBrace channels to Azure queues?

**Comment by krontogiannis** [comment]
Those improvements are already used for all azure storage requests.
https://github.com/mbraceproject/MBrace.Azure/blob/master/src/MBrace.Azure.Runtime/Common/Config.fs#L183
```fsharp
    do ServicePointManager.DefaultConnectionLimit <- 512
    do ServicePointManager.Expect100Continue <- false
    do ServicePointManager.UseNagleAlgorithm <- false
```

but the channel implementation does not use Azure Queues, it uses Service Bus Queues.

**Comment by dsyme** [comment]
OK, I'll close this, I'd forgotten you're using Service Bus for queues.
