### ISSUE TITLE
Process.Kill() takes a long time to take effect

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Azure#89]
I started a CloudFlow which for whatever reason I wanted to stop. Got process handle, sent a Kill() - the status of it is Cancellation Requested - but this takes minutes or sometimes hours to take effect. In the meantime I can see that there's still stuff happening on the cluster because CPU utilisation is up.

**Comment by krontogiannis** [comment]
So there are two issues here:
* `Kill` is probably a bad choice of a name. What `Kill` does is a call to the process' `CancellationTokenSource.Cancel`. I will rename this in the next release, to avoid any confusion.
* MBrace uses cooperative cancellation (like a async).

If your code is doing heavy CPU work, it should probably [check for cancellation](https://msdn.microsoft.com/en-us/library/dd997364(v=vs.110).aspx).

**Comment by dsyme** [comment]
Agreed that the use of cooperative cancellation can mean things take a time to die if they are CPU-intensive with no cancellation checks.  That's currently by design
