### ISSUE TITLE
Console program hangs executing Balanced.map

### ISSUE THREAD

**Issue by misterspeedy** [mbraceproject/MBrace.Azure#90]
A very simple computation using Balanced.map hangs when executed in a Windows Console program but runs fine when done through scripting.

Console program:

```fsharp
// Created new cmd line solution in VS
// Added Mbrace.Azure (0.6.9-Alpha) using Nuget
// Used a 4 node mbrace cluster provisioned via Brisk

open MBrace.Azure
open MBrace.Azure.Client
open MBrace.Workflows.Cloud

[<AutoOpen>]
module ConnectionStrings =
    [<Literal>]
    let briskmbraceKit_Storage = @"DefaultEndpointsProtocol=xxx"
    [<Literal>]
    let briskmbraceKit_ServiceBus = @"Endpoint=xxx"

module Cluster = 
   let config = Configuration.Default
                  .WithStorageConnectionString(briskmbraceKit_Storage)
                  .WithServiceBusConnectionString(briskmbraceKit_ServiceBus)
   let cluster = Runtime.GetHandle(config)

[<EntryPoint>]
let main argv = 
   // Hangs here:
   let squares =
      [1 .. 100]
      |> Balanced.map (fun x -> x * x + 5)
      |> Cluster.cluster.Run

   for sq in squares do
      printfn "%i" sq

   0
```

The same computation runs fine when put into Isaac's training script (MBraceOnBriskStart) and run against the same cluster.

I've tried restarting the cluster.

**Comment by palladin** [comment]
Is it possible to remove 0.6.9 and install MBrace.Azure (0.6.8-Alpha) using Nuget, because I think that Brisk currently uses 0.6.8

**Comment by isaacabraham** [comment]
Correct.

**Comment by palladin** [comment]
@isaacabraham I think it will be very helpful to have MBrace.Azure version number somewhere in the clusters page
![brisk](https://cloud.githubusercontent.com/assets/917467/8333676/d3caf550-1a9c-11e5-82cc-936b1424dc88.png)

**Comment by isaacabraham** [comment]
Yep, it would. Currently we actually don't record MBrace numbers within Brisk - it's something we will add, most likely when we get to 1.0 (or perhaps sooner).

**Comment by misterspeedy** [comment]
Removed 0.6.8 and installed 0.8.8.  Now get this exception at this line:

   let cluster = Runtime.GetHandle(config)

System.TypeInitializationException was unhandled by user code
Message: An exception of type 'System.TypeInitializationException' occurred in Vagabond.dll but was not handled in user code
Additional information: The type initializer for '<StartupCode$Vagabond>.$Nessos.Vagabond.DependencyAnalysis' threw an exception.

**Comment by misterspeedy** [comment]
Ah, but looks like 0.6.8 only got installed on one project of the solution.  Down-versioning the other one

**Comment by misterspeedy** [comment]
Eventually recreated the entire project and added 0.6.8 using 

 Install-Package MBrace.Azure –IncludePrerelease -version 0.6.8-alpha

Get a similar exception, but this time in S3-related code:

System.TypeInitializationException was unhandled
Message: An unhandled exception of type 'System.TypeInitializationException' occurred in S3.dll
Additional information: The type initializer for '<StartupCode$S3>.$Sync' threw an exception.

This was code that was working when on 0.6.9.

I'm going to upgrade back to 0.6.9 for now and just not use Balanced.map.

**Comment by misterspeedy** [comment]
That last exception was due to not bringing across some S3 configuration when I recreated the project.  I've brought that across, so I am now running a version of my code which - other than the Balanced.map hanging issue - was working under 0.6.9.  But I'm getting a bunch of other mbrace exceptions.

What's the quickest route to bringing up a cluster running MBrace 0.6.9 so that I can be running the latest (albeit alpha) version of everything?

**Comment by palladin** [comment]
@isaacabraham Is it possible to upgrade Brisk to MBrace.Azure 0.6.9 
@misterspeedy I have tried your example with 
```
let squares =
      [1 .. 100]
      |> Balanced.map (fun x -> x * x + 5)
      |> Cluster.cluster.Run
```
and it works with 0.6.8 and Brisk.
Is it possible to verify that the example that you posted works with 0.6.8?

**Comment by isaacabraham** [comment]
Sure, will do it this weekend probably. Cheers.

**Comment by dsyme** [comment]
This worked ok for me when I checked it.  I think it must have been a version mismatch?  I suggest we close this out unless there is investigation going on?
