### ISSUE TITLE
Could not run cloud computation in remote service bus

### ISSUE THREAD

**Issue by jasonweiyi** [mbraceproject/MBrace.Azure#92]
When I try to run MBrace cloud computations remotely in Azure service bus, the computation never terminates. But the same computation works fine locally. The code I was trying to run is 1-hello-world.fsx in HandsOnTutorial.

Here are my results for cluster.ShowWorkers and ShowProcesses:

Workers                                                                                                                                     

Id  Status  % CPU / Cores  % Memory / Total(MB)  Network(ul/dl : KB/s)  Jobs  Hostname  Process Id  Heartbeat  Initialization Time 
 --  ------  -------------  --------------------  ---------------------  ----  --------  ----------  ---------  ------------------- 
val it : unit = ()
> 

Processes                                                                                                                                                              

Name                        Process Id  Status  Completed  Execution Time            Jobs           Result Type  Start Time                    Completion Time 
 ----                        ----------  ------  ---------  --------------            ----           -----------  ----------                    --------------- 
       cb42b51444a24e61bfbcac0e773df77b  Posted  False      00:12:03.5772656    0 /   0 /   0 /   1  string       7/22/2015 10:31:37 AM +00:00                  
       16f8ea2439a04365baa9d0a1480a01c9  Posted  False      00:11:40.5216100    0 /   0 /   0 /   1  string       7/22/2015 10:32:00 AM +00:00                  
       fefc9fb3575d4749a8ab0d317fdb4eb1  Posted  False      00:10:13.3931241    0 /   0 /   0 /   1  string       7/22/2015 10:33:27 AM +00:00                  

Jobs : Active / Faulted / Completed / Total
val it : unit = ()

A question is: I should see some items in the Workers result, right?

My configuration:
Visual Studio 2013
Azure SDK 2.7
MBrace.Core.0.9.14-alpha

**Comment by palladin** [comment]
Is it possible to check the MBrace.Azure version of your Brisk deployment?

**Comment by isaacabraham** [comment]
I believe it's running 0.6.10.

**Comment by palladin** [comment]
Ok.. so the MBrace.StarterKit is using an older version of MBrace.Azure

**Comment by palladin** [comment]
@jasonweiyi Try to deploy a new Brisk cluster with
![brisk](https://cloud.githubusercontent.com/assets/917467/8824933/39665598-3083-11e5-9585-bd22e7b1861b.png)

**Comment by jasonweiyi** [comment]
Ok. Thanks.

On Wed, Jul 22, 2015 at 1:06 PM, Nick Palladinos <notifications@github.com>
wrote:

> @jasonweiyi <https://github.com/jasonweiyi> Try to deploy a new Brisk
> cluster with
> [image: brisk]
> <https://cloud.githubusercontent.com/assets/917467/8824933/39665598-3083-11e5-9585-bd22e7b1861b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbraceproject/MBrace.Azure/issues/92#issuecomment-123696249>
> .
>



-- 
Jason Wei
Chair of Software Engineering, ETH Zurich

**Comment by palladin** [comment]
@jasonweiyi Pls check also the paket.dependecies file in MBrace.StarterKit for the version of MBrace.Azure. The MBrace.Azure version in brisk and in StarterKit must be the same.

**Comment by jasonweiyi** [comment]
I created a new cluster with MBrace 0.6.10 and now it works.

On Wed, Jul 22, 2015 at 1:44 PM, Nick Palladinos <notifications@github.com>
wrote:

> @jasonweiyi <https://github.com/jasonweiyi> Pls check also the
> paket.dependecies file in MBrace.StarterKit for the version of
> MBrace.Azure. The MBrace.Azure version in brisk and in StarterKit must be
> the same.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbraceproject/MBrace.Azure/issues/92#issuecomment-123708616>
> .
>



-- 
Jason Wei
Chair of Software Engineering, ETH Zurich

**Comment by palladin** [comment]
@jasonweiyi Super... have fun! (As a rule of thumb if the ShowWorkers is empty then "probably" is a version mismatch issue)

**Comment by jasonweiyi** [comment]
It is indeed quite fun. Thanks.

On Wed, Jul 22, 2015 at 1:49 PM, Nick Palladinos <notifications@github.com>
wrote:

> @jasonweiyi <https://github.com/jasonweiyi> Super... have fun! (As a rule
> of thumb if the ShowWorkers is empty then "probably" is a version mismatch
> issue)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbraceproject/MBrace.Azure/issues/92#issuecomment-123709541>
> .
>



-- 
Jason Wei
Chair of Software Engineering, ETH Zurich

**Comment by isaacabraham** [comment]
@palladin we really need a client/server version check to eagerly pop when this happens.

**Comment by palladin** [comment]
@krontogiannis Is there any possible check we could do?

**Comment by dsyme** [comment]
Well, we really need version-robust compatibility between server and client :)  I still hope we can get this - I fundamentally believe it is possible if we want it to happen, e.g. through version-robust naming of types and closures generated by the MBrace.Core and MBrace.Azure APIs, though it may come at a cost in the codebase.

**Comment by isaacabraham** [comment]
@dsyme agreed, that'd be preferable, but the current implementation could (i would hope) quickly implement some basic version compat checking - at the moment, it's just silence from the server. Also the default behaviour of mbrace azure is to have separate service bus etc. for each version. obviously in the future that would change I guess.
