### ISSUE TITLE
Brisk does not create Http Endpoints

### ISSUE THREAD

**Issue by slyons** [mbraceproject/MBrace.Azure#94]
Brisk does not seem to create Http/Tcp endpoints when deploying a cluster anymore, the documentation should be updated to reflect that.

Having better documentation about what's required to deploy your own service would be very handy as well.

**Comment by dsyme** [comment]
I don't think this was deliberate, I'll ask by email

**Comment by isaacabraham** [comment]
As far as I'm aware nothing has changed here - HTTP should be open on port 80 and TCP on 10100. Can you confirm that those are the ports you're testing?

**Comment by slyons** [comment]
After the deployment completes I see that no endpoints are defined for the service. Is there any way to confirm this?

-----Original Message-----

**Comment by slyons** [comment]
I just deployed a new cluster and the endpoints are now available. Not sure why it didn't happen last time.
