### ISSUE TITLE
Cannot Add Lastest Version

### ISSUE THREAD

**Issue by sirinath** [mbraceproject/MBrace.Azure#95]
I get the following error:

```
Attempting to gather dependencies information for package 'MBrace.Azure.0.6.10-alpha' with respect to project 'Dagger', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'MBrace.Azure.0.6.10-alpha' with DependencyBehavior 'Lowest'
Install-Package : Unable to resolve dependencies. 'MBrace.Core 0.9.14-alpha' is not compatible with 'MBrace.Azure 0.6.10-alpha 
constraint: MBrace.Core (= 0.9.12-alpha)', 'MBrace.Runtime.Core 0.9.12-alpha constraint: MBrace.Core (= 0.9.12-alpha)'.
At line:1 char:1
+ Install-Package MBrace.Azure -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by krontogiannis** [comment]
The latest mbrace.azure is not compatible with `MBrace.Core 0.9.14`, try using `0.9.12` instead.

**Comment by palladin** [comment]
I tried Install-Package MBrace.Azure -Pre and I got
```
PM> Install-Package MBrace.Azure -Pre
Attempting to resolve dependency 'MBrace.Core (= 0.9.12-alpha)'.
Attempting to resolve dependency 'MBrace.Runtime.Core (= 0.9.12-alpha)'.
Attempting to resolve dependency 'Vagabond (= 0.6.9)'.
Attempting to resolve dependency 'Mono.Cecil (= 0.9.6.1)'.
Attempting to resolve dependency 'FsPickler (≥ 1.2.2 && < 1.3.0)'.
Attempting to resolve dependency 'FsPickler.Json'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 6.0.5)'.
Attempting to resolve dependency 'FsPickler (= 1.2.21)'.
Attempting to resolve dependency 'FsPickler (= 1.2.7)'.
Install-Package : Updating 'FsPickler 1.2.21' to 'FsPickler 1.2.7' failed. Unable to find a version of 'FsPickler.Json' that is compatibl
e with 'FsPickler 1.2.7'.
At line:1 char:1
+ Install-Package MBrace.Azure -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
```

**Comment by sirinath** [comment]
Can you make the releases that the latest of both work with each other?

**Comment by isaacabraham** [comment]
@palladin This has been the case since 0.6.10 - you have to manually specify the version of FSPickler.JSON to get it to work as I recall. cc: @krontogiannis, @eiriktsarpalis

**Comment by sirinath** [comment]
This is not a great user experience for someone trying to get your hands dirty MBrace.Azure for the 1st time.

**Comment by eiriktsarpalis** [comment]
> Can you make the releases that the latest of both work with each other?

Nope, MBrace.Core and MBrace.Azure are separate projects. It takes a bit of time to roll out a version of MBrace.Azure that targets the latest core, naturally the one will always be ahead of the other.

**Comment by sirinath** [comment]
OK. Can you put out a compatibility table out with this information?

**Comment by palladin** [comment]
@sirinath For a great 1st time user experience try
https://github.com/mbraceproject/MBrace.StarterKit
you can find tutorials about how to setup your cluster
https://github.com/mbraceproject/MBrace.StarterKit/blob/master/azure/AZURE.md
and a very comprehensive set of hands on tutorials that will help you to understand the basic concepts and learn the most basic api calls 
https://github.com/mbraceproject/MBrace.StarterKit/tree/master/azure/HandsOnTutorial

**Comment by palladin** [comment]
@sirinath You can always check the paket dependencies from the StarterKit
https://github.com/mbraceproject/MBrace.StarterKit/blob/master/paket.dependencies

**Comment by krontogiannis** [comment]
Fixed in https://github.com/mbraceproject/MBrace.Azure/commit/2097e9f96f43d13f954ccb7c20b71987b084b758
